// lib/gmat-data.ts
// ---------------------------------------------------------------------------
// GMAT Focus Edition — static question banks (NO database; git-versioned).
// Mirrors lib/ielts-reading-academic-data.ts: content lives in TypeScript and
// is consumed through lib/gmat-engine.ts. Components must NEVER hardcode items.
//
// All questions are ORIGINAL — they do not reproduce GMAC's copyrighted items.
// Every item carries a real `explanation`; MCQ items populate
// `optionExplanations` (per-option "why wrong") so the results screen teaches.
//
// Score is an ESTIMATE only — the official adaptive 205–805 scale cannot be
// reproduced from raw answers. The UI labels every score accordingly.
// ---------------------------------------------------------------------------

import type {
  GmatForm,
  GmatSectionBank,
  GmatSection,
} from "./gmat-types";

/* ======================================================================= */
/*  QUANTITATIVE REASONING  —  Problem Solving                              */
/* ======================================================================= */

const QUANT_ITEMS: GmatSectionBank["items"] = [
  {
    id: "gmat-ps-0001", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Arithmetic · rates",
    stem: "A train travels 240 miles in 4 hours. Travelling at the same constant speed, how far will it travel in 7 hours?",
    options: ["360 miles", "400 miles", "420 miles", "480 miles", "560 miles"],
    correct: 2,
    optionExplanations: [
      "This uses 6 hours, not 7 (60 × 6).",
      "This multiplies the speed by an incorrect factor.",
      "Speed = 240 ÷ 4 = 60 mph, so 60 × 7 = 420 miles.",
      "This uses 8 hours (60 × 8).",
      "This doubles the original distance instead of scaling to 7 hours.",
    ],
    explanation: "Find the constant speed first: 240 ÷ 4 = 60 mph. Then distance = speed × time = 60 × 7 = 420 miles.",
  },
  {
    id: "gmat-ps-0002", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Arithmetic · percents",
    stem: "After a 20% discount, a shirt sells for $80. What was its original price?",
    options: ["$96", "$100", "$104", "$120", "$160"],
    correct: 1,
    optionExplanations: [
      "This adds 20% to $80, but $80 is already the discounted price.",
      "$80 is 80% of the original, so original = 80 ÷ 0.80 = $100.",
      "This applies an incorrect percentage adjustment.",
      "This treats $80 as a 33% discount result.",
      "This doubles the price rather than reversing a 20% cut.",
    ],
    explanation: "A 20% discount leaves 80% of the original price. So 0.80 × original = 80, giving original = 80 ÷ 0.80 = $100.",
  },
  {
    id: "gmat-ps-0003", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Algebra · linear equations",
    stem: "If 3x + 7 = 22, what is the value of x?",
    options: ["3", "5", "7", "9", "15"],
    correct: 1,
    optionExplanations: [
      "This forgets to subtract 7 before dividing.",
      "3x = 22 − 7 = 15, so x = 15 ÷ 3 = 5.",
      "This divides 22 by 3 incorrectly.",
      "This adds 7 instead of subtracting it.",
      "This is 3x, not x.",
    ],
    explanation: "Subtract 7 from both sides: 3x = 15. Divide by 3: x = 5.",
  },
  {
    id: "gmat-ps-0004", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · ratios",
    stem: "Two numbers are in the ratio 2 : 3 and their sum is 40. What is the larger number?",
    options: ["16", "20", "24", "26", "28"],
    correct: 2,
    optionExplanations: [
      "This is the smaller number (2 parts).",
      "This splits 40 evenly instead of by the ratio.",
      "Total parts = 5; each part = 40 ÷ 5 = 8; larger = 3 × 8 = 24.",
      "This adds an extra part incorrectly.",
      "This uses a 2 : 5 split rather than 2 : 3.",
    ],
    explanation: "The ratio 2 : 3 has 5 parts. Each part = 40 ÷ 5 = 8. The larger number is 3 × 8 = 24.",
  },
  {
    id: "gmat-ps-0005", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Statistics · averages",
    stem: "The average of 5 numbers is 18. If one number, 30, is removed, what is the average of the remaining 4 numbers?",
    options: ["12", "13.5", "15", "16", "18"],
    correct: 2,
    optionExplanations: [
      "This subtracts too much from the running total.",
      "This divides an incorrect remaining sum.",
      "Sum of 5 = 90; remove 30 → 60; average of 4 = 60 ÷ 4 = 15.",
      "This forgets to remove the value fully.",
      "The average must change once a number above the mean is removed.",
    ],
    explanation: "Total of 5 numbers = 5 × 18 = 90. Removing 30 leaves 60 across 4 numbers, so the new average is 60 ÷ 4 = 15.",
  },
  {
    id: "gmat-ps-0006", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Arithmetic · work rates",
    stem: "Machine A completes a job in 6 hours and Machine B completes the same job in 12 hours. Working together, how long do they take?",
    options: ["3 hours", "4 hours", "4.5 hours", "8 hours", "9 hours"],
    correct: 1,
    optionExplanations: [
      "This halves the faster machine's time without combining rates.",
      "Combined rate = 1/6 + 1/12 = 1/4 job per hour, so time = 4 hours.",
      "This averages the rates incorrectly.",
      "This averages the two times (6 and 12) — rates must be added, not times.",
      "This is closer to summing the times than combining rates.",
    ],
    explanation: "Add rates: 1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4 of the job per hour. Time = 1 ÷ (1/4) = 4 hours.",
  },
  {
    id: "gmat-ps-0007", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Arithmetic · exponents",
    stem: "What is the value of 2^5 × 2^3?",
    options: ["64", "128", "256", "512", "1024"],
    correct: 2,
    optionExplanations: [
      "This is 2^6.",
      "This is 2^7.",
      "Same base: add exponents → 2^(5+3) = 2^8 = 256.",
      "This is 2^9.",
      "This is 2^10.",
    ],
    explanation: "When multiplying powers of the same base, add the exponents: 2^5 × 2^3 = 2^8 = 256.",
  },
  {
    id: "gmat-ps-0008", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Geometry · area",
    stem: "A rectangle has length 12 and width 5. What is its area?",
    options: ["17", "34", "48", "60", "120"],
    correct: 3,
    optionExplanations: [
      "This is the sum of length and width.",
      "This is the perimeter (2 × (12 + 5)).",
      "This uses an incorrect width.",
      "Area = length × width = 12 × 5 = 60.",
      "This doubles the area.",
    ],
    explanation: "Area of a rectangle = length × width = 12 × 5 = 60.",
  },
  {
    id: "gmat-ps-0009", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Probability",
    stem: "A bag holds 3 red and 2 blue marbles. If one marble is drawn at random, what is the probability it is red?",
    options: ["1/5", "2/5", "1/2", "3/5", "2/3"],
    correct: 3,
    optionExplanations: [
      "This is the probability of a single specific marble.",
      "This is the probability of drawing blue.",
      "This assumes equal counts of each colour.",
      "Favourable ÷ total = 3 red ÷ 5 marbles = 3/5.",
      "This uses an incorrect total of 3 instead of 5.",
    ],
    explanation: "Probability = favourable outcomes ÷ total outcomes = 3 ÷ (3 + 2) = 3/5.",
  },
  {
    id: "gmat-ps-0010", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Number properties · primes",
    stem: "What is the smallest prime number greater than 50?",
    options: ["51", "52", "53", "55", "57"],
    correct: 2,
    optionExplanations: [
      "51 = 3 × 17, not prime.",
      "52 is even, not prime.",
      "53 has no divisors other than 1 and itself — it is prime.",
      "55 = 5 × 11, not prime.",
      "57 = 3 × 19, not prime.",
    ],
    explanation: "Check each candidate above 50: 51 = 3 × 17, 52 is even, 53 is prime. So 53 is the smallest prime greater than 50.",
  },
  {
    id: "gmat-ps-0011", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · percent change",
    stem: "A quantity increases from 50 to 65. What is the percent increase?",
    options: ["15%", "23%", "25%", "30%", "35%"],
    correct: 3,
    optionExplanations: [
      "This is the raw increase, not the percent.",
      "This divides by the new value instead of the original.",
      "This rounds incorrectly.",
      "Increase = 15; percent = 15 ÷ 50 = 0.30 = 30%.",
      "This overstates the change.",
    ],
    explanation: "Percent increase = (new − old) ÷ old = (65 − 50) ÷ 50 = 15 ÷ 50 = 30%.",
  },
  {
    id: "gmat-ps-0012", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Arithmetic · rates",
    stem: "A car travels at a constant 60 miles per hour. How long does it take to travel 150 miles?",
    options: ["2 hours", "2.25 hours", "2.5 hours", "2.75 hours", "3 hours"],
    correct: 2,
    optionExplanations: [
      "This uses 120 miles.",
      "This is an incorrect division.",
      "Time = distance ÷ speed = 150 ÷ 60 = 2.5 hours.",
      "This rounds incorrectly.",
      "This uses 180 miles.",
    ],
    explanation: "Time = distance ÷ speed = 150 ÷ 60 = 2.5 hours.",
  },
  {
    id: "gmat-ps-0013", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · fractions",
    stem: "What is 3/4 + 1/6?",
    options: ["4/10", "5/6", "11/12", "1", "13/12"],
    correct: 2,
    optionExplanations: [
      "This adds numerators and denominators directly — not valid.",
      "This uses an incorrect common denominator.",
      "Common denominator 12: 9/12 + 2/12 = 11/12.",
      "This rounds up incorrectly.",
      "This overshoots; the sum is less than 1.",
    ],
    explanation: "Use a common denominator of 12: 3/4 = 9/12 and 1/6 = 2/12. Sum = 11/12.",
  },
  {
    id: "gmat-ps-0014", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Algebra · simultaneous equations",
    stem: "If 2x + y = 11 and x − y = 1, what is the value of x?",
    options: ["3", "4", "5", "6", "7"],
    correct: 1,
    optionExplanations: [
      "This solves for y, not x.",
      "Add the equations: 3x = 12, so x = 4.",
      "This adds incorrectly.",
      "This mis-substitutes the second equation.",
      "This uses the wrong sum of the equations.",
    ],
    explanation: "Add the two equations: (2x + y) + (x − y) = 11 + 1 → 3x = 12 → x = 4.",
  },
  {
    id: "gmat-ps-0015", section: "quant", type: "problem-solving",
    difficulty: "Easy", topic: "Arithmetic · simple interest",
    stem: "What is the simple interest on $1,000 at 5% per year for 3 years?",
    options: ["$50", "$100", "$150", "$300", "$1,150"],
    correct: 2,
    optionExplanations: [
      "This is one year of interest.",
      "This is two years of interest.",
      "Interest = principal × rate × time = 1000 × 0.05 × 3 = $150.",
      "This uses a 10% rate.",
      "This is principal plus interest, not the interest alone.",
    ],
    explanation: "Simple interest = P × r × t = 1000 × 0.05 × 3 = $150.",
  },
  {
    id: "gmat-ps-0016", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Sequences · arithmetic",
    stem: "In the arithmetic sequence 3, 7, 11, 15, …, what is the 10th term?",
    options: ["36", "39", "40", "43", "47"],
    correct: 1,
    optionExplanations: [
      "This uses 9 as the common difference's multiplier but the wrong first term.",
      "Term = a + (n−1)d = 3 + 9 × 4 = 39.",
      "This adds one extra difference.",
      "This uses n = 11.",
      "This overshoots by two terms.",
    ],
    explanation: "First term a = 3, common difference d = 4. The nth term = a + (n − 1)d = 3 + (10 − 1) × 4 = 3 + 36 = 39.",
  },
  {
    id: "gmat-ps-0017", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Geometry · circles",
    stem: "A circle has radius 7. Using π ≈ 22/7, what is its area?",
    options: ["44", "77", "132", "154", "308"],
    correct: 3,
    optionExplanations: [
      "This is roughly the circumference, not the area.",
      "This halves the area.",
      "This uses radius rather than radius squared incompletely.",
      "Area = πr² = (22/7) × 49 = 154.",
      "This doubles the correct area.",
    ],
    explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 22 × 7 = 154.",
  },
  {
    id: "gmat-ps-0018", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · mixtures",
    stem: "A 40-litre solution is 25% acid. How many litres of acid does it contain?",
    options: ["8", "10", "12", "15", "20"],
    correct: 1,
    optionExplanations: [
      "This uses 20% instead of 25%.",
      "Acid = 25% of 40 = 0.25 × 40 = 10 litres.",
      "This uses 30%.",
      "This uses an incorrect base volume.",
      "This uses 50%.",
    ],
    explanation: "Amount of acid = 25% × 40 = 0.25 × 40 = 10 litres.",
  },

  /* ---- Batch 2 (merged from verified set) ---- */
  {
    id: "gmat-ps-0019", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · rates",
    stem: "A printer prints at a constant rate of 90 pages every 4 minutes. How many minutes does it take to print 315 pages?",
    options: ["12", "13", "14", "15", "16"],
    correct: 2,
    explanation: "Rate = 90 ÷ 4 = 22.5 pages per minute. Time = 315 ÷ 22.5 = 14 minutes.",
    optionExplanations: [
      "Uses about 26 pages/min — too fast.",
      "Off-by-one slip in the division.",
      "Correct: 315 ÷ 22.5 = 14.",
      "Uses 21 pages/min.",
      "Rounds incorrectly upward.",
    ],
  },
  {
    id: "gmat-ps-0020", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Number properties",
    stem: "If n is a positive integer and n² is divisible by 72, what is the largest integer that MUST divide n?",
    options: ["6", "8", "12", "24", "36"],
    correct: 2,
    explanation: "72 = 2³·3². If n = 2^a·3^b·…, then n² = 2^(2a)·3^(2b)·…. We need 2a ≥ 3 (so a ≥ 2) and 2b ≥ 2 (so b ≥ 1). Thus n is divisible by 2²·3 = 12. (n = 12 works: 144 ÷ 72 = 2.)",
    optionExplanations: [
      "Only guarantees one factor of 2; two are required.",
      "Ignores the required factor of 3.",
      "Correct: n must contain 2²·3 = 12.",
      "Not guaranteed — 12 already suffices.",
      "Overcounts the power of 3.",
    ],
  },
  {
    id: "gmat-ps-0021", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · percents",
    stem: "A product's price is increased by 25% and then the new price is decreased by 20%. The final price is what percent of the original price?",
    options: ["95%", "100%", "105%", "110%", "120%"],
    correct: 1,
    explanation: "1.25 × 0.80 = 1.00, so the final price equals the original: 100%.",
    optionExplanations: [
      "Subtracts 25 − 20 = 5 incorrectly.",
      "Correct: 1.25 × 0.80 = 1.00.",
      "Adds the percentages.",
      "Misapplies the second percent.",
      "Compounds in the wrong direction.",
    ],
  },
  {
    id: "gmat-ps-0022", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Statistics · averages",
    stem: "The average (arithmetic mean) of 5 numbers is 20. If the number 40 is removed from the set, what is the average of the remaining 4 numbers?",
    options: ["12", "15", "16", "18", "20"],
    correct: 1,
    explanation: "Sum of the 5 numbers = 5 × 20 = 100. Remove 40 → 60 left over 4 numbers → 60 ÷ 4 = 15.",
    optionExplanations: [
      "Subtracts 8 by mistake.",
      "Correct: (100 − 40) ÷ 4 = 15.",
      "Divides 60 by the wrong count.",
      "Uses sum 112.",
      "Forgets to remove 40.",
    ],
  },
  {
    id: "gmat-ps-0023", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · work rates",
    stem: "Pump A can fill a tank in 6 hours and pump B can fill it in 4 hours. Working together, how many hours do they take to fill the tank?",
    options: ["2", "2.4", "2.5", "3", "5"],
    correct: 1,
    explanation: "Combined rate = 1/6 + 1/4 = 5/12 tank per hour. Time = 12/5 = 2.4 hours.",
    optionExplanations: [
      "Averages the two times wrongly.",
      "Correct: 1 ÷ (1/6 + 1/4) = 12/5 = 2.4.",
      "Uses rate 2/5.",
      "Takes half of 6.",
      "Adds the two times.",
    ],
  },
  {
    id: "gmat-ps-0024", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · exponents",
    stem: "If 2^x = 8, what is the value of 2^(x+2)?",
    options: ["10", "16", "24", "32", "64"],
    correct: 3,
    explanation: "2^x = 8 → x = 3. Then 2^(x+2) = 2^5 = 32.",
    optionExplanations: [
      "Adds 2 to 8.",
      "Multiplies 8 by 2 once.",
      "Adds 8 and 16.",
      "Correct: 2^5 = 32.",
      "Squares 8.",
    ],
  },
  {
    id: "gmat-ps-0025", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Probability",
    stem: "A bag contains 3 red and 2 blue marbles. If 2 marbles are drawn at random without replacement, what is the probability that both are red?",
    options: ["1/10", "1/5", "3/10", "2/5", "3/5"],
    correct: 2,
    explanation: "P = C(3,2) / C(5,2) = 3/10. (Or (3/5)(2/4) = 6/20 = 3/10.)",
    optionExplanations: [
      "Uses C(5,2) incorrectly.",
      "Forgets the without-replacement effect.",
      "Correct: 3/10.",
      "Counts ordered pairs.",
      "Adds probabilities.",
    ],
  },
  {
    id: "gmat-ps-0026", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Arithmetic · ratios",
    stem: "If a : b = 3 : 4 and b : c = 6 : 5, then a : c = ?",
    options: ["3 : 5", "9 : 10", "6 : 5", "4 : 5", "5 : 6"],
    correct: 1,
    explanation: "Make b common (LCM of 4 and 6 = 12): a : b = 9 : 12 and b : c = 12 : 10. So a : c = 9 : 10.",
    optionExplanations: [
      "Ignores the scaling of b.",
      "Correct: a : c = 9 : 10.",
      "Copies b : c.",
      "Uses a : b only.",
      "Inverts the relationship.",
    ],
  },
  {
    id: "gmat-ps-0027", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Algebra · word problem",
    stem: "Tickets cost $8 for adults and $5 for children. A group buys 20 tickets for $139. How many child tickets were bought?",
    options: ["3", "7", "9", "11", "13"],
    correct: 1,
    explanation: "Let c = child tickets. 8(20 − c) + 5c = 139 → 160 − 3c = 139 → 3c = 21 → c = 7.",
    optionExplanations: [
      "Solves for adults − children.",
      "Correct: c = 7.",
      "Sign error on the 3c term.",
      "Uses total 145.",
      "Swaps the prices.",
    ],
  },
  {
    id: "gmat-ps-0028", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Number properties · remainders",
    stem: "When the positive integer k is divided by 7, the remainder is 4. What is the remainder when 3k is divided by 7?",
    options: ["1", "2", "3", "5", "6"],
    correct: 3,
    explanation: "k = 7q + 4 → 3k = 21q + 12 = 7(3q + 1) + 5. Remainder = 5.",
    optionExplanations: [
      "Multiplies the remainder incorrectly.",
      "Adds remainders.",
      "Uses k itself.",
      "Correct: remainder 5.",
      "Off by one.",
    ],
  },
  {
    id: "gmat-ps-0029", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Arithmetic · mixtures",
    stem: "A 40-litre solution is 30% acid. How many litres of pure acid must be added to make the solution 50% acid?",
    options: ["8", "12", "16", "20", "24"],
    correct: 2,
    explanation: "Acid now = 12 L. Add x litres of pure acid: (12 + x) / (40 + x) = 0.5 → 12 + x = 20 + 0.5x → 0.5x = 8 → x = 16.",
    optionExplanations: [
      "Uses a 20% gap on 40.",
      "Solves the 0.3 equation.",
      "Correct: x = 16.",
      "Adds until the total is 60.",
      "Doubles the acid.",
    ],
  },
  {
    id: "gmat-ps-0030", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Algebra · linear equations",
    stem: "If 3(x − 2) = 2x + 5, what is x?",
    options: ["−11", "1", "7", "11", "13"],
    correct: 3,
    explanation: "3x − 6 = 2x + 5 → x = 11.",
    optionExplanations: [
      "Sign error throughout.",
      "Drops a term.",
      "Forgets to distribute.",
      "Correct: x = 11.",
      "Adds instead of subtracting.",
    ],
  },
  {
    id: "gmat-ps-0031", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Sets",
    stem: "In a class of 30 students, 18 study French and 15 study Spanish. If 5 study neither, how many study both?",
    options: ["3", "5", "8", "10", "12"],
    correct: 2,
    explanation: "Studying at least one = 30 − 5 = 25. Both = 18 + 15 − 25 = 8.",
    optionExplanations: [
      "Subtracts 'neither' twice.",
      "Uses 30 directly.",
      "Correct: 8.",
      "Adds 'neither'.",
      "Ignores the overlap.",
    ],
  },
  {
    id: "gmat-ps-0032", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · profit",
    stem: "A retailer buys an item for $80 and sells it at a 35% markup on cost. What is the selling price?",
    options: ["$104", "$108", "$112", "$115", "$120"],
    correct: 1,
    explanation: "Markup = 0.35 × 80 = 28. Selling price = 80 + 28 = $108.",
    optionExplanations: [
      "Uses a 30% markup.",
      "Correct: $108.",
      "Uses a 40% markup.",
      "Adds 35 flat.",
      "Marks up on the selling price.",
    ],
  },
  {
    id: "gmat-ps-0033", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Sequences · arithmetic",
    stem: "In an arithmetic sequence, the 3rd term is 11 and the 7th term is 27. What is the 1st term?",
    options: ["1", "3", "5", "7", "9"],
    correct: 1,
    explanation: "Common difference d = (27 − 11) / (7 − 3) = 4. First term = 11 − 2d = 11 − 8 = 3.",
    optionExplanations: [
      "Uses d = 3.",
      "Correct: 3.",
      "Adds instead of subtracting d.",
      "Uses d = 5.",
      "Off by one term.",
    ],
  },
  {
    id: "gmat-ps-0034", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Counting",
    stem: "How many different 3-digit numbers can be formed using the digits 1, 2, 3, 4, 5 if no digit repeats?",
    options: ["10", "20", "60", "120", "125"],
    correct: 2,
    explanation: "5 × 4 × 3 = 60.",
    optionExplanations: [
      "Uses C(5,3).",
      "Uses 5 × 4.",
      "Correct: 5 × 4 × 3 = 60.",
      "Uses 5!.",
      "Allows repeats (5³).",
    ],
  },
  {
    id: "gmat-ps-0035", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · percents",
    stem: "A number increased by 20% gives 96. What is the number?",
    options: ["72", "76", "80", "84", "115"],
    correct: 2,
    explanation: "1.2x = 96 → x = 80.",
    optionExplanations: [
      "Subtracts 20% of 96.",
      "Uses 1.25.",
      "Correct: 80.",
      "Uses 1.15.",
      "Adds 20% to 96.",
    ],
  },
  {
    id: "gmat-ps-0036", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Arithmetic · distance",
    stem: "Two cars start from the same point and travel in opposite directions at 50 km/h and 70 km/h. After how many hours are they 360 km apart?",
    options: ["2", "2.5", "3", "4", "5"],
    correct: 2,
    explanation: "Separation rate = 50 + 70 = 120 km/h. Time = 360 ÷ 120 = 3 hours.",
    optionExplanations: [
      "Uses only one speed.",
      "Uses rate 144.",
      "Correct: 360 ÷ 120 = 3.",
      "Uses the difference 20.",
      "Halves the distance.",
    ],
  },
  {
    id: "gmat-ps-0037", section: "quant", type: "problem-solving",
    difficulty: "Medium", topic: "Arithmetic · fractions",
    stem: "If 2/5 of a number is 18, what is 3/4 of that number?",
    options: ["27", "30", "33.75", "36", "45"],
    correct: 2,
    explanation: "Number = 18 ÷ (2/5) = 45. Then (3/4)(45) = 33.75.",
    optionExplanations: [
      "Takes 3/5 of 45.",
      "Uses the number 40.",
      "Correct: 33.75.",
      "Takes 4/5.",
      "Uses the number 60.",
    ],
  },
  {
    id: "gmat-ps-0038", section: "quant", type: "problem-solving",
    difficulty: "Hard", topic: "Number properties · units digit",
    stem: "What is the units digit of 7^23?",
    options: ["1", "3", "7", "9", "5"],
    correct: 1,
    explanation: "Units digits of 7^n cycle 7, 9, 3, 1 with period 4. 23 mod 4 = 3 → third in the cycle = 3.",
    optionExplanations: [
      "Uses 7^24 (units digit 1).",
      "Correct: 3.",
      "Uses 7^1.",
      "Uses 7^22 (units digit 9).",
      "7^n never ends in 5.",
    ],
  },
];

/* ======================================================================= */
/*  VERBAL REASONING  —  Critical Reasoning + Reading Comprehension         */
/* ======================================================================= */

const VERBAL_ITEMS: GmatSectionBank["items"] = [
  {
    id: "gmat-cr-0001", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · weaken",
    passage: "After the city installed protected bike lanes on Main Street, the number of reported cycling accidents on that street fell by 40% over the following year. The transport department concluded that protected bike lanes make cycling safer.",
    stem: "Which of the following, if true, most weakens the department's conclusion?",
    options: [
      "Many cyclists, fearing the construction, simply stopped riding on Main Street during that year.",
      "Protected bike lanes were also installed on two other streets in the same city.",
      "The city spent more on the bike lanes than it had originally budgeted.",
      "Cycling accidents in neighbouring towns rose slightly during the same period.",
      "Most cyclists surveyed said they preferred riding in protected lanes.",
    ],
    correct: 0,
    optionExplanations: [
      "If far fewer cyclists used Main Street, the drop in accidents could reflect lower ridership, not greater safety — directly undermining the causal claim.",
      "More lanes elsewhere does not address whether the lanes caused the safety improvement.",
      "Cost is irrelevant to the safety conclusion.",
      "Accidents elsewhere do not explain the Main Street drop.",
      "Preference is not the same as a measurable safety effect.",
    ],
    explanation: "The conclusion assumes the lanes caused safer cycling. If ridership fell sharply, fewer accidents may simply reflect fewer cyclists — an alternative cause that weakens the argument.",
  },
  {
    id: "gmat-cr-0002", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · assumption",
    passage: "A publisher plans to increase profits by raising the price of its flagship magazine by 15%. It expects total revenue to rise as a result.",
    stem: "The publisher's plan relies on which of the following assumptions?",
    options: [
      "The magazine's production costs will fall next year.",
      "The number of subscribers will not drop enough to offset the higher price.",
      "Competing magazines will also raise their prices.",
      "Readers prefer print magazines to digital ones.",
      "The magazine will win an industry award.",
    ],
    correct: 1,
    optionExplanations: [
      "Lower costs would affect profit but the claim here is about revenue from the price rise.",
      "Revenue = price × quantity. The plan only works if the quantity sold does not fall enough to cancel the price gain — this is the necessary assumption.",
      "Competitors' pricing is not required for this plan to succeed.",
      "Format preference is irrelevant to the revenue calculation.",
      "An award is unrelated to the revenue projection.",
    ],
    explanation: "Raising price increases revenue only if the resulting drop in quantity sold is small enough. The plan assumes subscriber losses will not offset the higher per-unit price.",
  },
  {
    id: "gmat-cr-0003", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · strengthen",
    passage: "A nutritionist argues that a new breakfast cereal improves concentration, citing a study in which students who ate the cereal scored higher on a midday focus test than those who skipped breakfast entirely.",
    stem: "Which of the following, if true, most strengthens the nutritionist's argument?",
    options: [
      "The students who ate the cereal also reported enjoying its taste.",
      "Students who ate a different breakfast scored no higher than those who skipped breakfast.",
      "Students who ate the cereal scored higher than students who ate a calorie-matched alternative breakfast.",
      "The cereal is fortified with several vitamins.",
      "The focus test was administered by trained staff.",
    ],
    correct: 2,
    optionExplanations: [
      "Enjoyment does not establish a concentration benefit.",
      "This actually undercuts the cereal's special role by suggesting any breakfast — or none — yields similar results.",
      "Comparing the cereal to an equivalent breakfast isolates the cereal itself as the cause, ruling out 'just eating something' — this strengthens the claim.",
      "Fortification is suggestive but does not show a measured concentration effect.",
      "Test administration quality does not bear on the cereal's effect.",
    ],
    explanation: "The original study only compared the cereal to skipping breakfast. Showing the cereal beats a calorie-matched breakfast isolates the cereal as the cause, strengthening the conclusion.",
  },
  {
    id: "gmat-cr-0004", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · inference",
    passage: "Every employee who completed the advanced training received a certification. No employee in the logistics department completed the advanced training.",
    stem: "Which of the following must be true?",
    options: [
      "No employee in the logistics department is certified.",
      "Some logistics employees completed a different training.",
      "All certified employees work outside logistics.",
      "The advanced training is required for promotion.",
      "Logistics employees are less skilled than others.",
    ],
    correct: 0,
    optionExplanations: [
      "Certification here comes only via the advanced training, which no logistics employee completed — so none of them obtained it this way. Within the stated facts, none are certified.",
      "Nothing is stated about other trainings.",
      "Certified employees could exist in any department that did the training; the statement does not say all are outside logistics.",
      "Promotion requirements are never mentioned.",
      "Skill comparisons are not supported by the premises.",
    ],
    explanation: "The only stated route to certification is the advanced training, and no logistics employee completed it. Therefore, based solely on these facts, no logistics employee is certified.",
  },
  {
    id: "gmat-cr-0005", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · flaw",
    passage: "A columnist writes: 'The best-selling car in the country last year was also the most frequently stolen. Clearly, this model has a security defect that thieves exploit.'",
    stem: "The columnist's reasoning is most vulnerable to the criticism that it",
    options: [
      "relies on a survey with too few respondents.",
      "fails to consider that the most common car would naturally be stolen most often simply because there are more of them.",
      "assumes that car thieves act rationally.",
      "draws a conclusion about the future from past data.",
      "confuses the cost of the car with its popularity.",
    ],
    correct: 1,
    optionExplanations: [
      "No survey is involved in the argument.",
      "Because the model is the most common on the road, it is the largest target pool — high theft counts may reflect sheer numbers, not a defect. The columnist overlooks this base-rate effect.",
      "The rationality of thieves is not the gap in the argument.",
      "The argument is about a defect, not a future prediction.",
      "Cost is never mentioned.",
    ],
    explanation: "The argument ignores base rates: the most common car is the most available target, so it may be stolen most often simply due to numbers, not a security defect.",
  },
  {
    id: "gmat-cr-0006", section: "verbal", type: "critical-reasoning",
    difficulty: "Easy", topic: "Critical Reasoning · weaken",
    passage: "A café owner noticed that sales of hot chocolate are highest in December. She concludes that cold weather causes people to crave hot chocolate.",
    stem: "Which of the following, if true, most weakens this conclusion?",
    options: [
      "Hot chocolate is also available in summer.",
      "December sales are driven largely by a seasonal holiday promotion offering hot chocolate at half price.",
      "The café sells more coffee than hot chocolate overall.",
      "Some customers add marshmallows to their hot chocolate.",
      "The café is located in a cold climate.",
    ],
    correct: 1,
    optionExplanations: [
      "Year-round availability does not explain the December spike.",
      "If a half-price promotion drives December sales, price — not cold weather — may be the real cause, weakening the weather explanation.",
      "Relative coffee sales are irrelevant to the hot-chocolate claim.",
      "Toppings have no bearing on the cause of demand.",
      "A cold climate is consistent with, not a challenge to, the conclusion.",
    ],
    explanation: "A confounding cause — the half-price holiday promotion — offers an alternative explanation for the December spike, weakening the claim that cold weather is the driver.",
  },
  {
    id: "gmat-cr-0007", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · assumption",
    passage: "A school plans to improve test scores by extending the school day by one hour. Administrators are confident this will raise average scores.",
    stem: "The plan depends on the assumption that",
    options: [
      "teachers will be paid more for the longer day.",
      "the additional hour will be used in ways that actually improve learning.",
      "students prefer longer school days.",
      "the school has enough classrooms.",
      "parents will approve of the change.",
    ],
    correct: 1,
    optionExplanations: [
      "Teacher pay does not determine whether scores rise.",
      "Extra time only helps if it is spent productively; without effective use, more hours need not raise scores. This is the necessary link.",
      "Student preference is not required for scores to improve.",
      "Classroom capacity is a logistical detail, not the core assumption.",
      "Parental approval does not affect the causal claim about scores.",
    ],
    explanation: "Adding time only raises scores if that time is used effectively for learning. The plan assumes the extra hour will be spent in a way that improves outcomes.",
  },
  {
    id: "gmat-cr-0008", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · evaluate",
    passage: "A manufacturer claims its new lightbulb lasts longer than the leading brand because, in lab tests, it burned for more hours before failing.",
    stem: "Which of the following would be most useful to know in evaluating the manufacturer's claim?",
    options: [
      "Whether the lab tests used the same on/off cycling that consumers typically subject bulbs to.",
      "How much the new bulb costs at retail.",
      "Whether the manufacturer advertises on television.",
      "What colour of light the new bulb produces.",
      "How many employees the manufacturer has.",
    ],
    correct: 0,
    optionExplanations: [
      "Bulb lifespan depends heavily on usage patterns; if the lab tests did not mirror real-world on/off cycling, the longer burn time may not translate to real longevity. This is decisive for evaluation.",
      "Price is irrelevant to a longevity comparison.",
      "Advertising channel has no bearing on lifespan.",
      "Light colour does not affect the longevity claim.",
      "Workforce size is unrelated to product performance.",
    ],
    explanation: "Whether the test conditions reflect typical consumer use (especially on/off cycling) determines whether the lab result supports the real-world longevity claim.",
  },
  {
    id: "gmat-cr-0009", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · strengthen",
    passage: "A city replaced the timed traffic signals at a busy intersection with a roundabout. In the year that followed, the number of injury-causing collisions there dropped sharply. Officials credit the roundabout for the improvement.",
    stem: "Which of the following, if true, most strengthens the officials' explanation?",
    options: [
      "Traffic volume through the intersection remained roughly the same before and after the change.",
      "The roundabout was more expensive to build than new signals would have been.",
      "Drivers reported that the roundabout was confusing at first.",
      "A nearby intersection that kept its signals saw no change in collisions.",
      "The city plans to build more roundabouts elsewhere.",
    ],
    correct: 0,
    optionExplanations: [
      "If traffic volume was unchanged, the drop in collisions cannot be explained away by fewer cars using the intersection — this supports the roundabout as the cause.",
      "Cost has no bearing on whether the roundabout reduced collisions.",
      "Initial confusion would, if anything, weaken the claim.",
      "An unchanged nearby intersection is a weak control but does not directly rule out a volume drop at the changed intersection.",
      "Future plans do not strengthen the causal claim about the existing change.",
    ],
    explanation: "A key alternative explanation is that fewer cars used the intersection. Confirming that traffic volume held steady removes that alternative, strengthening the claim that the roundabout caused the safety gain.",
  },
  {
    id: "gmat-cr-0010", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · paradox",
    passage: "A bookstore moved its most popular titles from the front of the store to the back. Surprisingly, total sales of all books rose in the following month, even though sales of those popular titles themselves stayed about the same.",
    stem: "Which of the following best explains the rise in total sales?",
    options: [
      "The popular titles were already selling at their maximum possible rate.",
      "To reach the popular titles at the back, customers now walk past many other books and often buy some of them.",
      "The store reduced the price of its popular titles.",
      "Fewer customers visited the store that month.",
      "The store hired additional staff for the month.",
    ],
    correct: 1,
    optionExplanations: [
      "This explains why popular-title sales were flat but not why total sales rose.",
      "Routing customers past other books exposes them to additional titles they then buy, raising total sales while popular-title sales stay flat — this resolves the paradox.",
      "A price cut would tend to change popular-title sales, which stayed the same.",
      "Fewer customers would tend to lower, not raise, total sales.",
      "More staff does not by itself explain higher total sales.",
    ],
    explanation: "Placing popular titles at the back forces customers to pass other books on the way, prompting extra purchases. That lifts total sales even though the popular titles' own sales are unchanged.",
  },
  {
    id: "gmat-cr-0011", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · assumption",
    passage: "A software firm will let employees work from home permanently, reasoning that eliminating commutes will make employees more productive.",
    stem: "The firm's reasoning depends on assuming that",
    options: [
      "employees currently spend a long time commuting.",
      "time and energy saved from commuting will translate into work output rather than being absorbed by other activities.",
      "the firm will save money on office space.",
      "all employees prefer working from home.",
      "competitors are also adopting remote work.",
    ],
    correct: 1,
    optionExplanations: [
      "Even a long commute does not guarantee a productivity gain; this is not the necessary link.",
      "The plan only works if the freed-up time and energy actually become work output instead of leisure or chores — the essential assumption.",
      "Office-space savings are a separate benefit, not the productivity claim.",
      "Employee preference is not required for productivity to rise.",
      "Competitor behaviour is irrelevant to this firm's productivity reasoning.",
    ],
    explanation: "Removing commutes raises productivity only if the saved time and energy convert into work rather than being spent elsewhere. The argument assumes that conversion happens.",
  },
  {
    id: "gmat-rc-0001", section: "verbal", type: "reading-comprehension",
    difficulty: "Medium", topic: "Reading Comprehension · social science",
    explanation: "Each sub-question is explained individually below.",
    passage:
      "For much of the twentieth century, economists treated the household as a single decision-making unit, as though a family shared one set of preferences. Beginning in the 1980s, however, a number of researchers challenged this 'unitary' model. They argued that households are better understood as arenas of negotiation, in which members with distinct preferences bargain over how resources are allocated.\n\nEvidence for this 'collective' view came from studies of how income affected spending. When income controlled by women rose relative to income controlled by men, spending patterns shifted — for instance, toward children's health and education. Under a strict unitary model, the source of a household's income should not affect how it is spent, since the household supposedly pools everything and spends according to shared priorities. The observed shifts therefore undermined the unitary assumption.\n\nCritics of the collective model concede that it fits the data better but note that it is harder to apply, since it requires information about each member's preferences and bargaining power — information that is often unavailable. The debate thus illustrates a recurring tension in economics between models that are tractable and models that are realistic.",
    questions: [
      {
        id: "gmat-rc-0001-q1",
        stem: "The primary purpose of the passage is to",
        options: [
          "describe a shift in how economists model household decision-making and the trade-off it reveals.",
          "prove that the unitary model of the household is entirely without merit.",
          "argue that women should control household income.",
          "trace the history of economics from the nineteenth century to the present.",
          "recommend a specific policy for improving children's health.",
        ],
        correct: 0,
        optionExplanations: [
          "The passage presents the move from the unitary to the collective model and ends on the tractability-vs-realism trade-off — an accurate statement of purpose.",
          "The passage says the collective model fits better but does not declare the unitary model worthless; it notes the unitary model's tractability.",
          "The passage uses income-control findings as evidence, not as a policy recommendation about who should control income.",
          "The passage focuses on a specific debate since the 1980s, not a sweeping history.",
          "No health policy is recommended.",
        ],
        explanation: "The passage explains the move from the unitary to the collective model and closes by framing the broader tractability-versus-realism trade-off — that is its main purpose.",
      },
      {
        id: "gmat-rc-0001-q2",
        stem: "According to the passage, the finding that spending shifted when women's relative income rose is significant because it",
        options: [
          "confirmed that households pool all income.",
          "contradicted a prediction of the unitary model.",
          "showed that men and women have identical preferences.",
          "proved that the collective model is easy to apply.",
          "demonstrated that income has no effect on spending.",
        ],
        correct: 1,
        optionExplanations: [
          "The finding undercut pooling, not confirmed it.",
          "The unitary model predicts the income source should not affect spending; the observed shift contradicted that prediction.",
          "The shift implies differing, not identical, preferences.",
          "The passage says the collective model is harder, not easier, to apply.",
          "Income clearly did affect spending, which is the opposite of this option.",
        ],
        explanation: "Under the unitary model, who earns the income should not change spending. The observed shift contradicted that prediction, supporting the collective view.",
      },
      {
        id: "gmat-rc-0001-q3",
        stem: "The passage suggests that critics of the collective model object to it primarily on the grounds that it",
        options: [
          "fits the empirical data poorly.",
          "requires information that is frequently unavailable.",
          "ignores the role of income entirely.",
          "was developed before the 1980s.",
          "applies only to households without children.",
        ],
        correct: 1,
        optionExplanations: [
          "Critics concede it fits the data better, so this is contradicted.",
          "The passage states the model needs data on each member's preferences and bargaining power, which is often unavailable — the critics' main objection.",
          "The model centres on income control, so it does not ignore income.",
          "The collective model emerged in the 1980s, and timing is not the objection.",
          "No such restriction to childless households is mentioned.",
        ],
        explanation: "Critics accept the collective model's better fit but object that it demands detailed information on members' preferences and bargaining power, which is often unavailable.",
      },
    ],
  },
  {
    id: "gmat-rc-0002", section: "verbal", type: "reading-comprehension",
    difficulty: "Hard", topic: "Reading Comprehension · science",
    explanation: "Each sub-question is explained individually below.",
    passage:
      "Coral reefs occupy less than one percent of the ocean floor, yet they support roughly a quarter of all marine species. This disproportionate richness has long puzzled ecologists, because the waters surrounding many reefs are strikingly low in the dissolved nutrients that usually fuel biological productivity. The apparent paradox — abundant life in nutrient-poor water — is sometimes called 'Darwin's paradox,' after the naturalist who first remarked on it.\n\nThe leading resolution centres on efficiency rather than supply. Reef organisms recycle nutrients with unusual thoroughness: waste produced by one organism is rapidly absorbed by another, so the same atoms of nitrogen and phosphorus cycle through the community many times before being lost. Symbiotic relationships are central to this thrift. Reef-building corals, for example, host photosynthetic algae within their tissues; the algae supply the coral with energy, and the coral supplies the algae with nutrients and shelter.\n\nThis tight coupling, however, is also a vulnerability. When water temperatures rise even slightly above the normal maximum, corals expel their algae — a process known as bleaching — and lose their principal energy source. If the stress is brief, corals may recover; if it is prolonged, they die. Because the entire reef economy rests on this partnership, the loss of the algae can cascade through the community, dismantling in months an ecosystem that took millennia to assemble.",
    questions: [
      {
        id: "gmat-rc-0002-q1",
        stem: "The passage indicates that 'Darwin's paradox' refers to the puzzle of",
        options: [
          "why coral reefs occupy so little of the ocean floor.",
          "how abundant life can flourish in nutrient-poor waters.",
          "why corals expel their algae when temperatures rise.",
          "how marine species evolved from land animals.",
          "why reefs take millennia to assemble.",
        ],
        correct: 1,
        optionExplanations: [
          "The small area is context, not the paradox itself.",
          "The passage defines the paradox as abundant life in nutrient-poor water — exactly this option.",
          "Bleaching is discussed later and is not the paradox named after Darwin.",
          "The passage makes no claim about marine species evolving from land animals.",
          "Assembly time is mentioned at the end, not as the paradox.",
        ],
        explanation: "The passage explicitly names the paradox as the coexistence of abundant life with nutrient-poor surrounding waters.",
      },
      {
        id: "gmat-rc-0002-q2",
        stem: "According to the passage, reefs sustain such rich life primarily because they",
        options: [
          "receive a steady supply of dissolved nutrients.",
          "recycle nutrients with unusual efficiency.",
          "occupy warm, shallow waters.",
          "are protected from temperature change.",
          "contain few competing species.",
        ],
        correct: 1,
        optionExplanations: [
          "The passage stresses that surrounding waters are nutrient-poor, so steady supply is not the answer.",
          "The passage attributes the richness to thorough nutrient recycling — 'efficiency rather than supply.'",
          "Warm shallow water is not given as the cause of the richness.",
          "The passage shows reefs are highly sensitive to temperature, not protected from it.",
          "High species richness contradicts 'few competing species.'",
        ],
        explanation: "The passage resolves the paradox through efficiency: reef organisms recycle nitrogen and phosphorus many times, sustaining life despite low external supply.",
      },
      {
        id: "gmat-rc-0002-q3",
        stem: "The passage suggests that the coral–algae symbiosis is best described as",
        options: [
          "beneficial but also a source of vulnerability.",
          "harmful to the coral but helpful to the algae.",
          "irrelevant to the reef's productivity.",
          "a recent development in reef ecosystems.",
          "unaffected by changes in water temperature.",
        ],
        correct: 0,
        optionExplanations: [
          "The passage calls the partnership central to the reef's thrift yet a vulnerability under heat stress — both at once.",
          "The relationship benefits the coral (energy) as well as the algae, so it is not one-sided harm.",
          "The symbiosis is described as central to productivity, not irrelevant.",
          "The passage gives no timeline suggesting it is recent.",
          "Temperature rises trigger bleaching, so the symbiosis is clearly temperature-sensitive.",
        ],
        explanation: "The passage frames the symbiosis as the engine of the reef's nutrient efficiency yet also its key weakness, since heat-driven bleaching can collapse the whole system.",
      },
    ],
  },

  /* ---- Batch 2 (merged from verified set) ---- */
  {
    id: "gmat-cr-0012", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · weaken",
    passage: "City planners argue that adding a dedicated bus lane on Riverside Avenue will reduce overall road congestion, because buses will no longer be delayed by car traffic.",
    stem: "Which of the following, if true, most weakens the planners' argument?",
    options: [
      "Most Riverside commuters already travel by bus.",
      "The bus lane will be created by removing one of the avenue's existing car lanes.",
      "The lane will be repainted every two years.",
      "Other cities have added similar bus lanes.",
      "Bus ridership rises slightly in winter.",
    ],
    correct: 1,
    explanation: "The conclusion is about OVERALL congestion. If the lane is taken from existing car lanes, the remaining cars are squeezed into fewer lanes and car congestion can rise — undercutting the overall claim.",
    optionExplanations: [
      "Tempting, but if most already ride buses the lane helps even more — it does not weaken.",
      "Correct: fewer car lanes can worsen overall congestion.",
      "Irrelevant to congestion.",
      "Precedent does not address this city's congestion.",
      "A minor seasonal detail with no impact on the conclusion.",
    ],
  },
  {
    id: "gmat-cr-0013", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · assumption",
    passage: "A company found that employees who use its new project-management software complete tasks 15% faster than those who do not. The company concludes that requiring all employees to use the software will raise overall productivity.",
    stem: "The argument depends on which of the following assumptions?",
    options: [
      "The software is inexpensive to license.",
      "Employees who chose to use the software were not already faster workers for other reasons.",
      "Competitors do not use similar software.",
      "All tasks can be tracked by the software.",
      "The software will be updated regularly.",
    ],
    correct: 1,
    explanation: "Classic correlation-vs-causation. If the voluntary users were already faster, the speed gap is not caused by the software, and mandating it will not raise productivity. The argument assumes that is not the case.",
    optionExplanations: [
      "Cost does not bear on the productivity inference.",
      "Correct: rules out the self-selection alternative cause.",
      "Competitors are irrelevant to internal productivity.",
      "Coverage of tasks is not required for the conclusion.",
      "Future updates are not assumed by the conclusion.",
    ],
  },
  {
    id: "gmat-cr-0014", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · strengthen",
    passage: "A nutritionist claims that a city's new tax on sugary drinks caused the 10% drop in soda sales there last year.",
    stem: "Which of the following, if true, most strengthens the claim?",
    options: [
      "Soda prices rose nationally last year.",
      "In neighboring cities without the tax, soda sales were unchanged over the same period.",
      "The city also opened several new parks last year.",
      "Diet soda is exempt from the tax.",
      "The tax revenue funded health programs.",
    ],
    correct: 1,
    explanation: "Showing that comparable cities WITHOUT the tax saw no drop isolates the tax as the cause and rules out a general trend.",
    optionExplanations: [
      "National price rises would affect everyone — this weakens isolation.",
      "Correct: a control group with no tax and no drop points to the tax.",
      "New parks introduce an alternative cause.",
      "An exemption detail does not establish causation.",
      "Use of the revenue is irrelevant to the cause of the drop.",
    ],
  },
  {
    id: "gmat-cr-0015", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · flaw",
    passage: "Editorial: Our newspaper's online articles that include video get more clicks than those without. Therefore, to increase total clicks, we should add video to every article.",
    stem: "The reasoning is most vulnerable to the criticism that it:",
    options: [
      "relies on a sample that is too small to be reliable",
      "assumes that what holds for some articles will hold for all, ignoring that video may suit only certain topics",
      "confuses a necessary condition with a sufficient one",
      "appeals to the opinions of experts without naming them",
      "draws a conclusion about costs from evidence about clicks",
    ],
    correct: 1,
    explanation: "The plan generalizes a pattern seen in some articles to ALL articles, ignoring that video may only boost certain topics and could even hurt others. That over-generalization is the flaw.",
    optionExplanations: [
      "Sample size is not the stated issue.",
      "Correct: an improper generalization from some to all.",
      "There is no necessary/sufficient confusion here.",
      "No expert appeal is made.",
      "Costs are not part of the conclusion.",
    ],
  },
  {
    id: "gmat-cr-0016", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · inference",
    passage: "All of the firm's senior analysts have completed the advanced certification. No junior analyst has completed it. Maria is an analyst at the firm who has completed the advanced certification.",
    stem: "Which of the following must be true?",
    options: [
      "Maria is the most experienced analyst.",
      "Maria is not a junior analyst.",
      "Every senior analyst is more skilled than Maria.",
      "Maria trains the junior analysts.",
      "Maria will be promoted soon.",
    ],
    correct: 1,
    explanation: "No junior analyst has the certification; Maria has it, so Maria cannot be a junior analyst. Nothing else is guaranteed.",
    optionExplanations: [
      "Experience is not established.",
      "Correct: having the certification rules out junior status.",
      "Relative skill is not stated.",
      "Training duties are not mentioned.",
      "Promotion is not supported.",
    ],
  },
  {
    id: "gmat-cr-0017", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · evaluate",
    passage: "A factory installed new machines and its monthly defect rate fell from 5% to 3%. Management credits the machines and plans to install them at a second factory.",
    stem: "Answering which question would be most useful in evaluating the plan?",
    options: [
      "What is the purchase price of each new machine?",
      "Did the first factory also change its quality-inspection process when it installed the machines?",
      "How many employees work at the second factory?",
      "What products does the second factory make?",
      "Who manufactures the new machines?",
    ],
    correct: 1,
    explanation: "If the inspection process changed at the same time, the defect drop might be due to inspection, not the machines — so the machines might not help the second factory. This question tests the causal link.",
    optionExplanations: [
      "Price does not evaluate the causal claim.",
      "Correct: isolates whether the machines or the inspection change caused the drop.",
      "Headcount does not bear on the cause.",
      "Product type is too vague to evaluate.",
      "Manufacturer identity is irrelevant.",
    ],
  },
  {
    id: "gmat-cr-0018", section: "verbal", type: "critical-reasoning",
    difficulty: "Medium", topic: "Critical Reasoning · weaken",
    passage: "A study found that people who take daily multivitamins report fewer colds. A health blog concludes that multivitamins prevent colds.",
    stem: "Which of the following, if true, most weakens the conclusion?",
    options: [
      "Multivitamins are widely available.",
      "People who take daily multivitamins also tend to exercise and sleep more than those who don't.",
      "The study included thousands of participants.",
      "Some multivitamins contain vitamin C.",
      "Colds are more common in winter.",
    ],
    correct: 1,
    explanation: "If multivitamin-takers also exercise and sleep more, those habits — not the vitamins — could explain the fewer colds, undercutting the causal conclusion.",
    optionExplanations: [
      "Availability is irrelevant.",
      "Correct: introduces confounding healthy habits.",
      "Large samples do not fix confounding.",
      "An ingredient detail does not establish cause.",
      "Seasonality applies to everyone.",
    ],
  },
  {
    id: "gmat-cr-0019", section: "verbal", type: "critical-reasoning",
    difficulty: "Hard", topic: "Critical Reasoning · assumption",
    passage: "To cut delivery times, an online retailer plans to build a warehouse closer to its largest customer region. It expects same-day delivery to that region as a result.",
    stem: "The plan assumes which of the following?",
    options: [
      "The new warehouse will be larger than existing ones.",
      "The retailer can stock the new warehouse with the items that region orders most.",
      "Competitors will not also build warehouses.",
      "Delivery drivers will accept lower pay.",
      "The region's population will grow.",
    ],
    correct: 1,
    explanation: "Same-day delivery requires that the nearby warehouse actually holds the ordered items; if it does not stock them, proximity will not deliver same-day. The plan assumes adequate local stock.",
    optionExplanations: [
      "Size is not required for same-day delivery to that region.",
      "Correct: proximity only helps if the items are in stock there.",
      "Competitor action is not assumed.",
      "Driver pay is not part of the plan.",
      "Population growth is not needed.",
    ],
  },
  {
    id: "gmat-rc-0003", section: "verbal", type: "reading-comprehension",
    difficulty: "Medium", topic: "Reading Comprehension · economics",
    explanation: "Each sub-question is explained individually below.",
    passage:
      "For decades, economists treated household savings purely as deferred consumption — money set aside to be spent later. Recent behavioral research complicates this view. Surveys show that many households hold precautionary savings they never intend to spend under ordinary circumstances; the balance itself provides a sense of security that functions as a form of consumption in the present. This reframing suggests that policies aimed at 'unlocking' idle savings may misread why the savings exist, and could leave households feeling materially worse off even when their measured spending power rises.",
    questions: [
      {
        id: "gmat-rc-0003-q1",
        stem: "The primary purpose of the passage is to:",
        options: [
          "argue for higher interest rates",
          "describe how a traditional economic assumption has been challenged",
          "prove that households should save more",
          "compare savings rates across countries",
          "criticize behavioral economists",
        ],
        correct: 1,
        explanation: "The passage states the traditional view, then shows research complicating it.",
        optionExplanations: [
          "Interest rates are not discussed.",
          "Correct.",
          "No such prescription is made.",
          "There is no cross-country comparison.",
          "It uses, rather than criticizes, that research.",
        ],
      },
      {
        id: "gmat-rc-0003-q2",
        stem: "According to the passage, policies to 'unlock' idle savings may fail because:",
        options: [
          "households lack banking access",
          "interest rates are too low",
          "the security provided by savings is itself a present benefit",
          "households do not know their balances",
          "spending power never rises",
        ],
        correct: 2,
        explanation: "The passage says the balance provides present security, so removing it can make households feel worse off.",
        optionExplanations: [
          "Not stated.",
          "Not the reason given.",
          "Correct.",
          "Contradicts the passage.",
          "The passage allows spending power to rise.",
        ],
      },
      {
        id: "gmat-rc-0003-q3",
        stem: "The passage implies that 'measured spending power' and household well-being:",
        options: [
          "are identical",
          "always move together",
          "can move in opposite directions",
          "cannot be quantified",
          "are set by policy",
        ],
        correct: 2,
        explanation: "Households can feel worse off even as spending power rises — so the two can diverge.",
        optionExplanations: [
          "The passage separates them.",
          "It shows they can diverge.",
          "Correct.",
          "Spending power is 'measured'.",
          "Not claimed.",
        ],
      },
    ],
  },
];

/* ======================================================================= */
/*  DATA INSIGHTS  —  DS, MSR, Table, Graphics, Two-Part                     */
/* ======================================================================= */

const DATA_INSIGHTS_ITEMS: GmatSectionBank["items"] = [
  /* ---- Data Sufficiency (options NEVER shuffled) ---- */
  {
    id: "gmat-ds-0001", section: "data-insights", type: "data-sufficiency",
    difficulty: "Medium", topic: "Data Sufficiency · algebra",
    stem: "What is the value of the integer x?",
    statements: ["x is a prime number between 10 and 20.", "x + 2 is a multiple of 13."],
    correct: 2,
    optionExplanations: [
      "Statement (1) alone leaves x as 11, 13, 17, or 19 — not unique.",
      "Statement (2) alone gives x + 2 ∈ {13, 26, …}, so x could be 11, 24, … — not unique.",
      "Together: x is prime in (10,20) and x + 2 is a multiple of 13, so x + 2 = 13 → x = 11, which is prime. Unique.",
      "Neither statement alone is sufficient, so 'each alone' is wrong.",
      "Together they pin down x = 11, so they are sufficient.",
    ],
    explanation: "(1) alone: primes 11, 13, 17, 19 — not unique. (2) alone: x = 11, 24, … — not unique. Together: x + 2 = 13 gives x = 11, which is prime and in range. Both together are sufficient; neither alone is.",
  },
  {
    id: "gmat-ds-0002", section: "data-insights", type: "data-sufficiency",
    difficulty: "Easy", topic: "Data Sufficiency · arithmetic",
    stem: "Is the integer n even?",
    statements: ["n is divisible by 6.", "n is divisible by 9."],
    correct: 0,
    optionExplanations: [
      "Statement (1): any multiple of 6 is divisible by 2, so n is even — sufficient alone.",
      "Statement (2): multiples of 9 can be odd (9, 27) or even (18), so not sufficient alone.",
      "Statement (1) already suffices, so 'both together' is not the best answer.",
      "Only (1) is sufficient, not each alone.",
      "(1) is sufficient, so the pair is not insufficient.",
    ],
    explanation: "(1) Multiples of 6 are always even — sufficient. (2) Multiples of 9 can be odd or even — not sufficient. So statement (1) alone is sufficient.",
  },
  {
    id: "gmat-ds-0003", section: "data-insights", type: "data-sufficiency",
    difficulty: "Hard", topic: "Data Sufficiency · word problem",
    stem: "A store sold pens and notebooks. How many pens were sold?",
    statements: ["The store sold 30 items in total.", "Each notebook sold for $4 and each pen for $1, and total sales were $75."],
    correct: 2,
    optionExplanations: [
      "Statement (1) alone gives pens + notebooks = 30 — many solutions.",
      "Statement (2) alone gives 4N + P = 75 — many solutions.",
      "Together: P + N = 30 and 4N + P = 75 → 3N = 45 → N = 15, P = 15. Unique.",
      "Neither alone works, so 'each alone' is wrong.",
      "Together they solve uniquely, so they are sufficient.",
    ],
    explanation: "(1): P + N = 30. (2): 4N + P = 75. Each alone is underdetermined. Subtracting gives 3N = 45, so N = 15 and P = 15. Together sufficient; neither alone.",
  },
  {
    id: "gmat-ds-0004", section: "data-insights", type: "data-sufficiency",
    difficulty: "Medium", topic: "Data Sufficiency · statistics",
    stem: "Is the average (arithmetic mean) of five different integers greater than 20?",
    statements: ["The smallest of the integers is 19.", "The largest of the integers is 21."],
    correct: 4,
    optionExplanations: [
      "Statement (1) alone: with a minimum of 19, the others could be small or large, so the mean could be above or below 20.",
      "Statement (2) alone: with a maximum of 21, the mean could be below or near 20.",
      "Even together, the three middle values are unknown, so the mean is not determined.",
      "Neither alone is sufficient.",
      "Together: integers are distinct with min 19 and max 21, but the three middle values still vary, so the mean cannot be pinned relative to 20 — insufficient.",
    ],
    explanation: "Knowing only the min (19) and max (21) of five distinct integers leaves the three middle values free, so the average could be above or below 20. Even together the statements are insufficient.",
  },
  /* ---- Two-Part Analysis (rows shuffle; both indices remap) ---- */
  {
    id: "gmat-tp-0001", section: "data-insights", type: "two-part-analysis",
    difficulty: "Medium", topic: "Two-Part Analysis · algebra",
    intro: "A company's total monthly cost C (in dollars) to produce q units is given by C = 500 + 8q. Its revenue R is R = 12q.",
    prompt: "Select the number of units that makes total cost equal to $1,300 in the first column, and the number of units at which revenue equals total cost (break-even) in the second column. Make one selection in each column.",
    colHeaders: ["Cost = $1,300", "Break-even"],
    rows: ["75", "100", "125", "150", "175"],
    correctA: 1, // 500 + 8q = 1300 → q = 100
    correctB: 2, // 12q = 500 + 8q → 4q = 500 → q = 125
    explanation: "Cost = $1,300: 500 + 8q = 1300 → 8q = 800 → q = 100. Break-even: 12q = 500 + 8q → 4q = 500 → q = 125.",
  },
  {
    id: "gmat-tp-0002", section: "data-insights", type: "two-part-analysis",
    difficulty: "Hard", topic: "Two-Part Analysis · proportions",
    intro: "A recipe requires sugar and flour in the ratio 2 : 5 by weight. A baker wants to make a batch using a whole number of grams of each.",
    prompt: "In the first column select a possible weight of sugar, and in the second column select the corresponding weight of flour for the same batch, keeping the 2 : 5 ratio. Make one selection in each column.",
    colHeaders: ["Sugar (g)", "Flour (g)"],
    rows: ["40", "60", "100", "150", "175"],
    correctA: 1, // sugar 60
    correctB: 3, // flour 150 (60:150 = 2:5)
    explanation: "For a 2 : 5 ratio, flour = 2.5 × sugar. Among the options, sugar = 60 g pairs with flour = 150 g, since 60 : 150 = 2 : 5.",
  },
  {
    id: "gmat-tp-0003", section: "data-insights", type: "two-part-analysis",
    difficulty: "Medium", topic: "Two-Part Analysis · logic",
    intro: "Two trains leave the same station. Train X travels north at 50 km/h; Train Y travels south at 70 km/h, both starting at noon.",
    prompt: "Select the distance Train X has travelled by 3:00 p.m. in the first column, and the total distance between the two trains at 3:00 p.m. in the second column. Make one selection in each column.",
    colHeaders: ["Train X distance", "Distance apart"],
    rows: ["120 km", "150 km", "210 km", "300 km", "360 km"],
    correctA: 1, // 50 × 3 = 150
    correctB: 4, // (50+70) × 3 = 360
    explanation: "In 3 hours Train X travels 50 × 3 = 150 km. The trains move apart at 50 + 70 = 120 km/h, so after 3 hours they are 120 × 3 = 360 km apart.",
  },
  /* ---- Table Analysis (statements shuffle; all must be correct) ---- */
  {
    id: "gmat-ta-0001", section: "data-insights", type: "table-analysis",
    difficulty: "Medium", topic: "Table Analysis · sales data",
    intro: "The table shows quarterly revenue (in $ thousands) for four regional offices. Sort the columns as needed, then judge each statement.",
    table: {
      columns: ["Office", "Q1", "Q2", "Q3", "Q4"],
      rows: [
        ["North", 120, 135, 150, 160],
        ["South", 90, 95, 80, 110],
        ["East", 200, 180, 210, 220],
        ["West", 75, 85, 95, 100],
      ],
    },
    answerLabels: ["Yes", "No"],
    statements: [
      { text: "East had the highest revenue in every quarter shown.", correct: true },
      { text: "West's revenue increased in every successive quarter.", correct: true },
      { text: "South's revenue increased in every successive quarter.", correct: false },
    ],
    explanation: "East (200, 180, 210, 220) leads every quarter — Yes. West rises 75 → 85 → 95 → 100 every quarter — Yes. South goes 90 → 95 → 80 → 110, dropping in Q3 — so 'increased every quarter' is No.",
  },
  {
    id: "gmat-ta-0002", section: "data-insights", type: "table-analysis",
    difficulty: "Hard", topic: "Table Analysis · demographics",
    intro: "The table lists five countries with their population (millions) and land area (thousand km²). Sort as needed, then evaluate each statement.",
    table: {
      columns: ["Country", "Population (M)", "Area (k km²)"],
      rows: [
        ["Alpha", 50, 500],
        ["Beta", 80, 400],
        ["Gamma", 20, 800],
        ["Delta", 120, 600],
        ["Epsilon", 30, 300],
      ],
    },
    answerLabels: ["Yes", "No"],
    statements: [
      { text: "Delta has the largest population of the five countries.", correct: true },
      { text: "Gamma has the lowest population density (people per km²) of the five.", correct: true },
      { text: "Beta has a larger land area than Alpha.", correct: false },
    ],
    explanation: "Delta's 120 M is the largest population — Yes. Density = population ÷ area: Gamma = 20/800 = 0.025 M per k km², the lowest — Yes. Beta's area is 400 vs Alpha's 500, so Beta is smaller — the statement is No.",
  },
  /* ---- Graphics Interpretation (each blank's options shuffle) ---- */
  {
    id: "gmat-gi-0001", section: "data-insights", type: "graphics-interpretation",
    difficulty: "Medium", topic: "Graphics Interpretation · bar chart",
    intro: "The bar chart shows the number of units sold by a shop over five months. Use it to complete each statement.",
    chart: {
      kind: "bars",
      labels: ["Jan", "Feb", "Mar", "Apr", "May"],
      values: [40, 55, 50, 70, 65],
      yLabel: "Units sold",
    },
    blanks: [
      { prefix: "The month with the highest sales was", options: ["April", "May", "February", "March"], correct: 0 },
      { prefix: "Sales first decreased between", options: ["Jan and Feb", "Feb and Mar", "Mar and Apr", "Apr and May"], correct: 1, suffix: "." },
    ],
    explanation: "Highest bar is April at 70 units. The first month-to-month decrease is Feb (55) to Mar (50).",
  },
  {
    id: "gmat-gi-0002", section: "data-insights", type: "graphics-interpretation",
    difficulty: "Hard", topic: "Graphics Interpretation · line trend",
    intro: "The line graph shows a city's average temperature (°C) over six months. Use it to complete each statement.",
    chart: {
      kind: "line",
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
      values: [5, 8, 12, 18, 23, 27],
      yLabel: "Avg temp (°C)",
    },
    blanks: [
      { prefix: "The temperature rose by the largest single-month amount between", options: ["Mar and Apr", "Apr and May", "Jan and Feb", "Feb and Mar"], correct: 0 },
      { prefix: "Over the whole period the trend is", options: ["steadily increasing", "steadily decreasing", "flat", "fluctuating up and down"], correct: 0, suffix: "." },
    ],
    explanation: "Month-to-month rises: +3, +4, +6, +5, +4 — the largest is Mar→Apr (+6). Across all six months the temperature only rises, so the trend is steadily increasing.",
  },
  /* ---- Multi-Source Reasoning (mcq sub-q options shuffle; yn fixed) ---- */
  {
    id: "gmat-msr-0001", section: "data-insights", type: "multi-source-reasoning",
    difficulty: "Hard", topic: "Multi-Source Reasoning · project",
    explanation: "Each sub-question is explained individually below.",
    sources: [
      {
        title: "Email",
        body: "From the project lead: 'The website redesign has three phases — Design, Build, and Test. Design must finish before Build starts, and Build must finish before Test starts. We have 9 weeks total before launch.'",
      },
      {
        title: "Schedule",
        body: "Estimated durations: Design = 3 weeks, Build = 4 weeks, Test = 2 weeks. No phase can overlap another.",
      },
    ],
    questions: [
      {
        id: "gmat-msr-0001-q1",
        kind: "mcq",
        stem: "If all phases run back-to-back with no delay, in which week does the Test phase begin?",
        options: ["Week 5", "Week 8", "Week 7", "Week 6"],
        correct: 1,
        explanation: "Design takes weeks 1–3, Build takes weeks 4–7, so Test begins in week 8.",
      },
      {
        id: "gmat-msr-0001-q2",
        kind: "yn",
        stem: "Based on the two sources, determine whether each statement is supported.",
        statements: [
          { text: "The three phases together fit within the 9-week window.", correct: true },
          { text: "Build can begin before Design is complete.", correct: false },
          { text: "There is at least 1 week of slack before launch.", correct: false },
        ],
        answerLabels: ["Yes", "No"],
        explanation: "Total duration = 3 + 4 + 2 = 9 weeks, exactly filling the 9-week window (fits — Yes; no slack — No). The email says Design must finish before Build starts, so Build cannot begin early — No.",
      },
    ],
  },

  /* ---- Batch 2 (merged from verified set) ---- */
  {
    id: "gmat-ds-0005", section: "data-insights", type: "data-sufficiency",
    difficulty: "Medium", topic: "Data Sufficiency · algebra",
    stem: "Is the integer x greater than 10?",
    statements: [
      "x is a multiple of 4.",
      "x is between 11 and 20, inclusive.",
    ],
    correct: 1,
    optionExplanations: [
      "Statement (1) alone: x could be 4, 8, or 12 — not always > 10.",
      "Statement (2) alone: 11 ≤ x ≤ 20 means x is always greater than 10 — sufficient.",
      "Statement (2) already suffices alone, so 'both together' is not the best answer.",
      "Only (2) is sufficient, not each alone.",
      "(2) is sufficient, so the pair is not insufficient.",
    ],
    explanation: "(1) x could be 4, 8, or 12 — not sufficient. (2) 11 ≤ x ≤ 20 is always greater than 10 — sufficient. Statement (2) alone is sufficient.",
  },
  {
    id: "gmat-ds-0006", section: "data-insights", type: "data-sufficiency",
    difficulty: "Hard", topic: "Data Sufficiency · number properties",
    stem: "Is the positive integer n even?",
    statements: [
      "n² is even.",
      "3n is even.",
    ],
    correct: 3,
    optionExplanations: [
      "Statement (1) alone is sufficient, but so is (2), so this is not the best answer.",
      "Statement (2) alone is sufficient, but so is (1), so this is not the best answer.",
      "Each statement alone already suffices, so 'both together' is not needed.",
      "Correct: (1) n² even → n even; (2) 3n even with 3 odd → n even. EACH alone is sufficient.",
      "Each statement alone is sufficient, so the pair is not insufficient.",
    ],
    explanation: "(1) If n² is even, n is even — sufficient. (2) 3n even and 3 is odd → n must be even — sufficient. EACH statement alone is sufficient.",
  },
  {
    id: "gmat-ta-0003", section: "data-insights", type: "table-analysis",
    difficulty: "Medium", topic: "Table Analysis · quarterly revenue",
    intro: "The table shows quarterly revenue (in $ millions) for four branches. Sort as needed, then evaluate each statement.",
    table: {
      columns: ["Branch", "Q1", "Q2", "Q3", "Q4"],
      rows: [
        ["North", 12, 14, 13, 18],
        ["South", 9, 8, 11, 10],
        ["East", 20, 19, 22, 21],
        ["West", 5, 7, 9, 12],
      ],
    },
    answerLabels: ["Yes", "No"],
    statements: [
      { text: "West's revenue increased in every quarter.", correct: true },
      { text: "East had the highest Q3 revenue of any branch.", correct: true },
      { text: "North's Q4 was more than double its Q1.", correct: false },
    ],
    explanation: "West 5 → 7 → 9 → 12 strictly increases (Yes). East Q3 = 22 is the maximum Q3 (Yes). North Q1 = 12 and Q4 = 18; double of 12 is 24 > 18, so the Q4 claim is No.",
  },
  {
    id: "gmat-tp-0004", section: "data-insights", type: "two-part-analysis",
    difficulty: "Hard", topic: "Two-Part Analysis · cost & break-even",
    intro: "A company's total monthly cost C (in $ thousands) is C = 8 + 0.5u, where u is the number of units produced. Revenue is R = 1.3u (in $ thousands).",
    prompt: "Select the units value at which total cost equals 20 in the first column, and the smallest integer units value at which revenue exceeds cost in the second column. Make one selection in each column.",
    colHeaders: ["Cost = 20", "Break-even"],
    rows: ["10", "11", "20", "24", "30"],
    correctA: 3, // 8 + 0.5u = 20 → u = 24
    correctB: 1, // 1.3u > 8 + 0.5u → 0.8u > 8 → u > 10 → smallest integer 11
    explanation: "Cost = 20: 8 + 0.5u = 20 → 0.5u = 12 → u = 24. Break-even: 1.3u > 8 + 0.5u → 0.8u > 8 → u > 10, so the smallest integer is 11.",
  },
  {
    id: "gmat-msr-0002", section: "data-insights", type: "multi-source-reasoning",
    difficulty: "Hard", topic: "Multi-Source Reasoning · shipping",
    explanation: "Use both sources together; see per-question explanations.",
    sources: [
      {
        title: "Email",
        body: "From Operations: We can ship via Carrier A (3-day, $400) or Carrier B (5-day, $250). The client needs delivery within 4 days.",
      },
      {
        title: "Policy",
        body: "Shipments must use the lowest-cost carrier that still meets the client's deadline. Expedited surcharges require manager approval.",
      },
    ],
    questions: [
      {
        id: "gmat-msr-0002-q1",
        kind: "mcq",
        stem: "Which carrier should be selected without further approval?",
        options: ["Carrier A", "Carrier B", "Neither", "Either is allowed", "Cannot be determined"],
        correct: 0,
        explanation: "The deadline is 4 days; Carrier B (5-day) misses it. Carrier A meets it and is the lowest-cost option that does. No surcharge is noted, so no extra approval is needed.",
      },
      {
        id: "gmat-msr-0002-q2",
        kind: "yn",
        stem: "Indicate whether each statement is supported by the sources.",
        statements: [
          { text: "Carrier B satisfies the client's deadline.", correct: false },
          { text: "Policy requires choosing the cheapest deadline-meeting carrier.", correct: true },
        ],
        answerLabels: ["Supported", "Not supported"],
        explanation: "Carrier B is 5-day against a 4-day deadline (not supported). The policy text states the cheapest deadline-meeting rule (supported).",
      },
    ],
  },
];

/* ======================================================================= */
/*  Section banks + full form                                              */
/* ======================================================================= */

export const QUANT_BANK: GmatSectionBank = {
  id: "quant", name: "Quantitative Reasoning", minutes: 45, realCount: 21,
  items: QUANT_ITEMS,
};

export const VERBAL_BANK: GmatSectionBank = {
  id: "verbal", name: "Verbal Reasoning", minutes: 45, realCount: 23,
  items: VERBAL_ITEMS,
};

export const DATA_INSIGHTS_BANK: GmatSectionBank = {
  id: "data-insights", name: "Data Insights", minutes: 45, realCount: 20,
  items: DATA_INSIGHTS_ITEMS,
};

export const GMAT_FORM: GmatForm = {
  id: "focus-mock-1", title: "GMAT Focus — Full Mock", editsPerSection: 3,
  sections: [QUANT_BANK, VERBAL_BANK, DATA_INSIGHTS_BANK],
};

export const getBank = (s: GmatSection): GmatSectionBank =>
  GMAT_FORM.sections.find((x) => x.id === s)!;
