// ─── Types ───────────────────────────────────────────────────────────────────

export type QuestionType = "mcq" | "tfng" | "ynng" | "sentence_completion" | "short_answer";

export interface Question {
  id: number;
  type: QuestionType;
  q: string;
  opts?: string[];          // MCQ: "A. text"
  answer: string;           // MCQ: "A"–"D" | TFNG: "TRUE"/"FALSE"/"NOT GIVEN" | YNNG: "YES"/"NO"/"NOT GIVEN" | text types: exact word/phrase
  acceptedAnswers?: string[]; // all acceptable forms for text types (lowercased comparison)
  explanation: string;
  sentenceTemplate?: string; // sentence_completion: the sentence with _____ marker
}

export interface Passage {
  id: string;
  title: string;
  tag: string;
  level: string;
  wordCount: number;
  text: string;
  questions: Question[];
}

// ─── Passages ────────────────────────────────────────────────────────────────

export const PASSAGES: Passage[] = [
  {
    id: "sleep-science",
    title: "The Science of Sleep",
    tag: "Academic",
    level: "Band 6–7",
    wordCount: 310,
    text: `Sleep is one of the most fundamental biological processes shared by nearly all animals. Despite spending roughly one-third of their lives asleep, humans have only recently begun to understand why sleep is so essential. Scientists now know that sleep serves multiple critical functions, including memory consolidation, cellular repair and immune system regulation.

During sleep, the brain cycles through distinct stages known as REM (Rapid Eye Movement) and non-REM sleep. Non-REM sleep, which occurs first, consists of three progressively deeper stages. The deepest stage, slow-wave sleep, is when the body performs most of its physical restoration. Growth hormone is released, muscles are repaired, and the immune system strengthens. REM sleep, by contrast, is characterised by vivid dreaming and is believed to be essential for emotional processing and memory formation.

Research conducted at the University of Berkeley demonstrated that sleep deprivation significantly impairs cognitive function. Subjects who slept fewer than six hours per night for two weeks showed cognitive deficits equivalent to two full nights of total sleep loss. Remarkably, these individuals reported feeling only slightly sleepy, suggesting that people often underestimate the impact of chronic sleep restriction on their performance.

Modern lifestyles present numerous threats to healthy sleep. Artificial light — particularly the blue light emitted by smartphones and tablets — suppresses melatonin production, the hormone responsible for signalling sleep onset. Additionally, the increasing demands of work and social commitments have led many people to view sleep as a luxury rather than a necessity. Sleep scientists argue that this cultural attitude must change if society is to address the growing epidemic of sleep-related health problems, including obesity, diabetes and cardiovascular disease.`,
    questions: [
      { id: 1, type: "tfng", q: "Humans have understood the importance of sleep for a very long time.", answer: "FALSE", explanation: "The passage states humans have 'only recently begun to understand why sleep is so essential', contradicting this statement." },
      { id: 2, type: "tfng", q: "Growth hormone is released during the deepest stage of non-REM sleep.", answer: "TRUE", explanation: "The passage explicitly states: 'Growth hormone is released, muscles are repaired' during slow-wave sleep (the deepest non-REM stage)." },
      { id: 3, type: "tfng", q: "The Berkeley study participants were fully aware of how impaired they had become.", answer: "FALSE", explanation: "The passage says they 'reported feeling only slightly sleepy', indicating they underestimated their impairment." },
      { id: 4, type: "mcq", q: "According to the passage, which function does REM sleep primarily serve?", opts: ["A. Physical restoration and muscle repair", "B. Immune system strengthening", "C. Emotional processing and memory formation", "D. Melatonin production"], answer: "C", explanation: "The passage states REM sleep 'is believed to be essential for emotional processing and memory formation'." },
      { id: 5, type: "mcq", q: "What does the writer suggest about society's view of sleep?", opts: ["A. It is appropriately valued as a health priority", "B. It needs to change to combat health problems", "C. It has improved thanks to scientific research", "D. It only affects younger generations"], answer: "B", explanation: "The passage says 'this cultural attitude must change if society is to address the growing epidemic of sleep-related health problems'." },
      { id: 6, type: "mcq", q: "What proportion of their lives do humans spend asleep?", opts: ["A. Approximately one quarter", "B. Approximately one third", "C. Approximately one half", "D. Approximately one fifth"], answer: "B", explanation: "The passage states humans spend 'roughly one-third of their lives asleep'." },
      { id: 7, type: "tfng", q: "The Berkeley study used participants who slept fewer than six hours per night for two weeks.", answer: "TRUE", explanation: "The passage states subjects 'slept fewer than six hours per night for two weeks'." },
      { id: 8, type: "sentence_completion", q: "Complete the sentence using NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Blue light emitted by smartphones and tablets suppresses the production of _____, the hormone responsible for signalling sleep onset.", answer: "melatonin", acceptedAnswers: ["melatonin"], explanation: "The passage states blue light 'suppresses melatonin production, the hormone responsible for signalling sleep onset'." },
      { id: 9, type: "short_answer", q: "Name ONE health problem linked to poor sleep that is mentioned in the final paragraph.", answer: "obesity", acceptedAnswers: ["obesity", "diabetes", "cardiovascular disease", "cardiovascular"], explanation: "The passage lists 'obesity, diabetes and cardiovascular disease' as sleep-related health problems." },
      { id: 10, type: "ynng", q: "The writer believes modern working culture has contributed to unhealthy sleep habits.", answer: "YES", explanation: "The writer states 'the increasing demands of work and social commitments have led many people to view sleep as a luxury rather than a necessity', implying criticism of modern culture." },
    ],
  },

  {
    id: "urban-farming",
    title: "The Rise of Urban Farming",
    tag: "Academic",
    level: "Band 7–8",
    wordCount: 330,
    text: `Urban farming — the practice of cultivating food within city environments — has experienced a remarkable resurgence in recent decades. Once viewed as a relic of wartime necessity, it is now celebrated as an innovative solution to some of the most pressing challenges of the 21st century, from food security to environmental sustainability.

Proponents of urban agriculture cite numerous benefits. Locally grown produce requires significantly less transportation, thereby reducing carbon emissions associated with the global food supply chain. Rooftop gardens and vertical farms can also mitigate the urban heat island effect, where cities absorb and retain heat at higher rates than surrounding rural areas. Furthermore, community gardens have been shown to foster social cohesion, reduce crime rates in neglected urban spaces, and provide therapeutic benefits to participants.

Critics, however, question whether urban farming can ever be more than a supplement to conventional agriculture. Land in cities is expensive and limited; the yields per square metre achieved by rooftop gardens are typically far lower than those of large-scale rural operations. Water usage can also be intensive, and not all urban environments receive sufficient sunlight to support productive cultivation year-round.

Technological innovations are beginning to address some of these constraints. Hydroponic and aeroponic systems allow crops to grow without soil, using up to 90% less water than traditional agriculture. LED lighting technology has made indoor farming viable in buildings with limited natural light. Some companies are now operating fully automated vertical farms in former warehouses, producing leafy greens and herbs at competitive costs. Whether these advances will allow urban farming to scale sufficiently to make a meaningful contribution to a city's food needs remains an open question.`,
    questions: [
      { id: 1, type: "mcq", q: "How does the writer describe the historical perception of urban farming?", opts: ["A. As an innovative modern concept", "B. As something associated with wartime", "C. As a leading agricultural method", "D. As a threat to rural farming"], answer: "B", explanation: "The passage states urban farming was 'once viewed as a relic of wartime necessity'." },
      { id: 2, type: "tfng", q: "Community gardens have been proven to eliminate crime in urban areas.", answer: "FALSE", explanation: "The passage says gardens 'reduce crime rates', not eliminate them. 'Proven to eliminate' is too strong and inaccurate." },
      { id: 3, type: "tfng", q: "Hydroponic systems use considerably less water than conventional farming.", answer: "TRUE", explanation: "The passage states these systems use 'up to 90% less water than traditional agriculture'." },
      { id: 4, type: "mcq", q: "Which of the following is NOT mentioned as a challenge facing urban farming?", opts: ["A. High land costs in cities", "B. Lower yields compared to rural farms", "C. Lack of consumer interest", "D. Insufficient sunlight in some locations"], answer: "C", explanation: "Lack of consumer interest is never mentioned. The passage raises land costs, lower yields and sunlight issues." },
      { id: 5, type: "mcq", q: "What is the writer's overall tone regarding the future of urban farming?", opts: ["A. Fully optimistic — urban farming will replace traditional agriculture", "B. Entirely negative — the challenges are insurmountable", "C. Cautiously uncertain — the potential is there but questions remain", "D. Indifferent — the topic is of little practical importance"], answer: "C", explanation: "The final sentence 'remains an open question' reflects cautious uncertainty, balanced between promise and unresolved challenges." },
      { id: 6, type: "tfng", q: "The urban heat island effect means cities retain heat at higher rates than rural areas.", answer: "TRUE", explanation: "The passage defines this as cities 'absorb and retain heat at higher rates than surrounding rural areas'." },
      { id: 7, type: "short_answer", q: "According to the passage, what percentage less water do hydroponic and aeroponic systems use compared to traditional agriculture?", answer: "90", acceptedAnswers: ["90", "90%", "up to 90", "up to 90%"], explanation: "The passage states these systems use 'up to 90% less water than traditional agriculture'." },
      { id: 8, type: "tfng", q: "Some companies are operating fully automated vertical farms in former warehouses.", answer: "TRUE", explanation: "The passage explicitly states 'some companies are now operating fully automated vertical farms in former warehouses'." },
      { id: 9, type: "ynng", q: "The author believes urban farming will definitively become a major food source for cities in the near future.", answer: "NOT GIVEN", explanation: "The author ends with 'remains an open question', expressing uncertainty rather than a clear positive or negative belief." },
      { id: 10, type: "sentence_completion", q: "Complete the sentence using NO MORE THAN THREE WORDS from the passage.", sentenceTemplate: "LED lighting technology has made indoor farming viable in buildings with _____.", answer: "limited natural light", acceptedAnswers: ["limited natural light"], explanation: "The passage states 'LED lighting technology has made indoor farming viable in buildings with limited natural light'." },
    ],
  },

  {
    id: "bilingualism",
    title: "The Neurological Architecture of Bilingualism",
    tag: "Academic",
    level: "Band 7–8",
    wordCount: 420,
    text: `For much of the twentieth century, bilingualism was viewed with suspicion by educators and psychologists alike. Early studies suggested that children raised speaking two languages simultaneously were at a cognitive disadvantage, experiencing what researchers described as "language confusion" — an apparent inability to keep the two linguistic systems separate. This deficit model dominated academic thinking for decades until more rigorous experimental methods overturned it entirely.

The revolution began in the 1960s with the work of Elizabeth Peal and Wallace Lambert at McGill University, whose study of French-English bilingual children in Montreal demonstrated that, far from being handicapped, bilingual individuals outperformed their monolingual counterparts on a range of intellectual tasks. Subsequent decades of research have confirmed and extended these findings, revealing that managing two language systems simultaneously exercises and strengthens the brain's executive control network — the set of neural processes responsible for attention, task-switching, conflict resolution, and inhibitory control.

Neuroimaging studies have provided anatomical evidence for these cognitive advantages. Research published in the journal Cerebral Cortex has shown that lifelong bilinguals possess greater grey matter density in the left inferior parietal cortex, a region associated with language processing and executive function. Additionally, functional MRI studies indicate that when a bilingual person speaks in one language, both languages remain simultaneously active in the brain, with the non-target language constantly suppressed. This ongoing neurological management is believed to strengthen the prefrontal cortex — the area most closely linked to planning, attention, and self-regulation.

Perhaps the most striking finding concerns the onset of neurodegenerative disease. Multiple large-scale clinical studies, including influential research from the Rotman Research Institute in Toronto, have found that Alzheimer's disease symptoms appear an average of four to five years later in bilingual patients compared with monolinguals, even after controlling for variables such as education level, immigration status, and cognitive activities. Researchers hypothesise that the constant exercise of managing two language systems builds what is termed "cognitive reserve" — a neural resilience that enables the brain to continue functioning normally despite the accumulating damage of disease.

It should be noted, however, that the concept of a "bilingual advantage" remains contested. Some researchers argue that publication bias — the tendency of journals to favour positive findings — has inflated the apparent benefits of bilingualism. A 2014 meta-analysis found that the advantage in executive function tasks disappeared when larger, more representative samples were used. What is generally agreed upon is that the brain is profoundly shaped by experience, and managing the complexity of two language systems is one of the most cognitively demanding experiences the human brain can undergo.`,
    questions: [
      { id: 1, type: "tfng", q: "Early twentieth-century researchers believed that bilingualism benefited children's cognitive development.", answer: "FALSE", explanation: "The passage states early studies believed bilingual children were 'at a cognitive disadvantage', not at a benefit." },
      { id: 2, type: "tfng", q: "The McGill University study involved children who spoke French and English.", answer: "TRUE", explanation: "The passage explicitly describes 'French-English bilingual children in Montreal' in the Peal and Lambert study." },
      { id: 3, type: "tfng", q: "Neuroimaging has confirmed that the non-target language is completely deactivated when a bilingual person speaks.", answer: "FALSE", explanation: "The passage states both languages remain 'simultaneously active', with the non-target language 'constantly suppressed' — not deactivated." },
      { id: 4, type: "mcq", q: "According to the passage, what does the term 'cognitive reserve' mean?", opts: ["A. The total number of languages a person speaks fluently", "B. A neural resilience built through cognitively demanding activity", "C. A region of the brain linked to executive language processing", "D. The capacity to switch rapidly between language tasks"], answer: "B", explanation: "The passage defines it as 'a neural resilience that enables the brain to continue functioning normally despite the accumulating damage of disease'." },
      { id: 5, type: "mcq", q: "What conclusion did the 2014 meta-analysis reach about the bilingual advantage?", opts: ["A. It proved the advantage was even larger than previously thought", "B. It confirmed clear benefits across all cognitive tasks studied", "C. It suggested the advantage may be overstated due to sample limitations", "D. It concluded bilingualism has no measurable cognitive effect"], answer: "C", explanation: "The passage states 'the advantage in executive function tasks disappeared when larger, more representative samples were used', suggesting overstatement." },
      { id: 6, type: "tfng", q: "All researchers in the field agree that bilingualism provides clear and measurable cognitive benefits.", answer: "FALSE", explanation: "The passage says the concept 'remains contested', with some researchers citing publication bias." },
      { id: 7, type: "mcq", q: "Why do bilingual brains appear to develop greater resilience against neurodegeneration, according to the passage?", opts: ["A. Bilinguals tend to have significantly higher levels of formal education", "B. The constant management of two active language systems exercises key brain regions", "C. Bilinguals engage in more varied leisure and cognitive activities", "D. The left inferior parietal cortex grows larger in all multilingual speakers"], answer: "B", explanation: "The passage explains that 'the constant exercise of managing two language systems builds cognitive reserve' — a form of neural resilience." },
      { id: 8, type: "short_answer", q: "In which journal was the neuroimaging study showing greater grey matter density in bilinguals published?", answer: "Cerebral Cortex", acceptedAnswers: ["cerebral cortex"], explanation: "The passage states the research was 'published in the journal Cerebral Cortex'." },
      { id: 9, type: "short_answer", q: "By how many years does the onset of Alzheimer's symptoms appear later in bilingual patients, according to the Toronto research?", answer: "four to five", acceptedAnswers: ["four to five", "4 to 5", "4-5", "four or five", "4 or 5"], explanation: "The passage states symptoms appear 'an average of four to five years later in bilingual patients'." },
      { id: 10, type: "tfng", q: "The Rotman Research Institute study controlled for education level when comparing bilingual and monolingual Alzheimer's patients.", answer: "TRUE", explanation: "The passage states the research controlled for 'variables such as education level, immigration status, and cognitive activities'." },
    ],
  },

  {
    id: "wood-wide-web",
    title: "The Subterranean Wood Wide Web",
    tag: "Academic",
    level: "Band 7–8",
    wordCount: 440,
    text: `Beneath the forest floor, invisible to the casual observer, lies a communications and nutrient-transfer network of extraordinary complexity. This underground system — informally termed the "Wood Wide Web" — consists of mycorrhizal fungi whose thread-like filaments, known as hyphae, extend through soil across vast distances, connecting the root systems of individual trees and plants in a living web of chemical exchange.

The relationship between trees and mycorrhizal fungi is one of the most ancient symbioses on Earth, believed to have originated approximately 450 million years ago when the first land plants began colonising terrestrial environments. In this mutualistic arrangement, fungi penetrate or surround plant root cells, dramatically increasing the surface area through which the plant can absorb water and mineral nutrients — particularly phosphorus and nitrogen, which are critical for growth but poorly accessible through root absorption alone. In exchange, the fungi receive sugars produced through the plant's photosynthesis, energy they cannot generate independently due to their inability to photosynthesize.

The Canadian ecologist Suzanne Simard's pioneering research in British Columbia during the 1990s demonstrated that this underground network facilitates not only nutrient absorption but active resource transfer between trees. Using radioactive carbon isotopes as tracers, Simard showed that carbon fixed by birch trees could be detected in the root systems of nearby Douglas firs within hours. Crucially, transfer appeared to be directional rather than random: mature "mother trees" — large, established individuals with extensive fungal networks — were found to channel disproportionately large quantities of nutrients toward younger, shaded seedlings of the same species, apparently sustaining seedlings that would otherwise perish in the low-light conditions of the forest understory.

This finding prompted significant debate about whether trees could be said to "communicate" or show forms of preferential behaviour. Critics argue that the nutrient flows observed are simply the result of diffusion gradients and passive chemical processes — trees are not deliberate agents. Supporters of Simard's interpretation point out that the patterns of transfer are too consistent and directional to be fully explained by simple diffusion, and that the network shows dynamic responsiveness to environmental stress. When one tree is attacked by insects, for instance, chemical defence signals appear to travel through the mycorrhizal network and prime neighbouring trees' own defence systems.

Beyond individual tree relationships, the mycorrhizal network has profound implications for forest resilience. Forests connected by rich fungal networks recover faster from disturbance — drought, disease, or selective logging — than fragmented forests where network integrity has been compromised. Forest management practices that ignore the underground dimension of forest ecology, such as clear-cutting or the heavy use of soil-disruptive machinery, may damage networks that took centuries to form. Conservation biologists increasingly argue that protecting the mycorrhizal web must become as central to forest management policy as protecting the trees themselves.`,
    questions: [
      { id: 1, type: "tfng", q: "The mycorrhizal network was first discovered by Suzanne Simard during her British Columbia research.", answer: "NOT GIVEN", explanation: "The passage describes Simard's research on resource transfer, but does not attribute the discovery of mycorrhizal fungi to her." },
      { id: 2, type: "tfng", q: "Mycorrhizal fungi are able to produce their own energy through photosynthesis.", answer: "FALSE", explanation: "The passage explicitly states fungi have an 'inability to photosynthesize' and cannot generate energy independently." },
      { id: 3, type: "mcq", q: "What did Simard's use of radioactive carbon isotopes demonstrate?", opts: ["A. That fungi produce sugars through a chemical process similar to photosynthesis", "B. That carbon from birch trees could be traced in the root systems of Douglas firs", "C. That young seedlings absorb more nutrients than mature trees", "D. That phosphorus is the primary nutrient transferred through the network"], answer: "B", explanation: "The passage states Simard 'showed that carbon fixed by birch trees could be detected in the root systems of nearby Douglas firs within hours'." },
      { id: 4, type: "tfng", q: "All scientists agree that trees deliberately direct nutrients toward seedlings through the fungal network.", answer: "FALSE", explanation: "Critics argue the transfers are 'simply the result of diffusion gradients and passive chemical processes', not deliberate tree behaviour." },
      { id: 5, type: "mcq", q: "What criticism do sceptics make of Simard's interpretation of the mycorrhizal network?", opts: ["A. That the network has no measurable effect on tree survival rates", "B. That radioactive tracers are an unreliable measurement method", "C. That the nutrient transfers result from passive chemical processes, not deliberate action", "D. That mother trees receive more nutrients than they contribute"], answer: "C", explanation: "Critics argue flows are 'the result of diffusion gradients and passive chemical processes', rejecting the idea of deliberate tree behaviour." },
      { id: 6, type: "mcq", q: "What does the writer suggest about forest management practices?", opts: ["A. Clear-cutting is necessary to allow younger trees to access fungal networks", "B. Modern logging technology has successfully preserved mycorrhizal networks", "C. The underground network deserves the same conservation priority as the trees above it", "D. Mycorrhizal networks naturally regenerate within a few years after disturbance"], answer: "C", explanation: "The passage concludes that 'protecting the mycorrhizal web must become as central to forest management policy as protecting the trees themselves'." },
      { id: 7, type: "tfng", q: "Forests with intact mycorrhizal networks recover more quickly from environmental stress than fragmented ones.", answer: "TRUE", explanation: "The passage states 'forests connected by rich fungal networks recover faster from disturbance… than fragmented forests where network integrity has been compromised'." },
      { id: 8, type: "short_answer", q: "What type of tracers did Simard use to track carbon transfer between trees in her research?", answer: "radioactive", acceptedAnswers: ["radioactive", "radioactive carbon isotopes", "radioactive isotopes", "carbon isotopes"], explanation: "The passage states Simard used 'radioactive carbon isotopes as tracers'." },
      { id: 9, type: "ynng", q: "The writer believes that trees are deliberate agents that intentionally direct nutrients toward weaker seedlings.", answer: "NOT GIVEN", explanation: "The writer presents both sides of the debate without endorsing either interpretation explicitly." },
      { id: 10, type: "sentence_completion", q: "Complete the sentence using NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "The mycorrhizal network originated approximately _____ million years ago when the first land plants began colonising terrestrial environments.", answer: "450", acceptedAnswers: ["450"], explanation: "The passage states the symbiosis is 'believed to have originated approximately 450 million years ago'." },
    ],
  },

  {
    id: "chronometer",
    title: "The Chronometer Revolution and the Problem of Longitude",
    tag: "Academic",
    level: "Band 7–8",
    wordCount: 450,
    text: `Of all the practical challenges that confronted maritime navigators in the Age of Exploration, none proved more persistently lethal than the problem of longitude. While determining latitude — a ship's north-south position — was achievable through straightforward astronomical observation of the sun's altitude or the angle of Polaris above the horizon, longitude required knowing the precise difference in time between the ship's current position and a fixed reference point. Since the Earth rotates 15 degrees per hour, a one-hour error in timekeeping translated to a positional error of over one hundred kilometres, enough to drive an entire fleet onto an uncharted reef.

The catastrophic scale of longitude-related maritime disasters prompted the British Parliament to establish, in 1714, the Board of Longitude, which offered a prize of £20,000 — equivalent to several million pounds in contemporary terms — to whoever could determine longitude at sea with an accuracy of half a degree. The scientific establishment of the day anticipated that the solution would come from astronomy — specifically from the "lunar distance" method, which required calculating a ship's longitude from the angle between the moon and certain fixed stars. This method, while theoretically sound, demanded hours of calculation and exceptional mathematical skill, making it impractical for everyday navigation.

The solution that ultimately prevailed came not from astronomy but from horology — the science of timekeeping. John Harrison, a self-taught carpenter and clockmaker from Lincolnshire, spent four decades designing a succession of marine timekeepers that could maintain accurate time aboard a ship despite the continuous motion, temperature fluctuations, and humidity of a sea voyage. His first three devices — the H1, H2, and H3 — were large, complex mechanisms that, though impressive, failed to meet the longitude prize's strict accuracy requirements. His fourth instrument, the H4, completed in 1759, was a revolutionary departure from his earlier designs: a compact, watch-like device that performed with stunning precision during its trial voyages to Jamaica.

Despite the H4's demonstrable success in sea trials, Harrison's claim to the full longitude prize was obstructed by Nevil Maskelyne, the Astronomer Royal, who was personally invested in the competing lunar distance method. Maskelyne dismissed Harrison's instruments as a practical solution and arranged for the official trials to be conducted in circumstances that he controlled. Harrison was compelled to petition King George III directly before Parliament eventually awarded him the full prize in 1773, at the age of eighty.

Harrison's chronometer did more than solve a navigational problem — it fundamentally transformed the nature of global commerce, warfare, and exploration. The ability to know one's precise longitudinal position enabled ship captains to chart accurate courses, reduce journey times, and navigate with a confidence that had been impossible for previous generations. The accurate maps produced from chronometer-assisted surveys redrew the world's coastlines and formed the geographic foundation upon which modern cartography is built.`,
    questions: [
      { id: 1, type: "tfng", q: "Latitude was more difficult to determine at sea than longitude during the Age of Exploration.", answer: "FALSE", explanation: "Latitude was 'achievable through straightforward astronomical observation', whereas longitude was the persistently difficult problem." },
      { id: 2, type: "mcq", q: "Why did the British Parliament offer the longitude prize?", opts: ["A. To encourage the development of better astronomical telescopes", "B. Because longitude errors had caused catastrophic maritime disasters", "C. To compete with rival European powers in navigation technology", "D. Because Harrison had already demonstrated the potential of marine timekeepers"], answer: "B", explanation: "The passage states 'the catastrophic scale of longitude-related maritime disasters' directly prompted Parliament to establish the prize." },
      { id: 3, type: "tfng", q: "The scientific establishment of 1714 expected the longitude solution to come from advances in clockmaking.", answer: "FALSE", explanation: "The passage states the establishment 'anticipated that the solution would come from astronomy', not horology." },
      { id: 4, type: "mcq", q: "What was John Harrison's main background before designing marine timekeepers?", opts: ["A. A trained naval navigator with practical sea experience", "B. A professional astronomer employed at a royal observatory", "C. A self-taught carpenter and clockmaker from Lincolnshire", "D. A mathematician engaged by the Board of Longitude"], answer: "C", explanation: "The passage describes Harrison as 'a self-taught carpenter and clockmaker from Lincolnshire'." },
      { id: 5, type: "tfng", q: "Harrison's H4 was similar in design to his three earlier marine timekeepers.", answer: "FALSE", explanation: "The passage describes the H4 as 'a revolutionary departure from his earlier designs' — a compact, watch-like device." },
      { id: 6, type: "mcq", q: "According to the passage, what role did Nevil Maskelyne play in relation to Harrison's prize claim?", opts: ["A. He publicly endorsed the H4 after its successful trial voyage", "B. He arranged impartial and fair tests of Harrison's instruments", "C. He obstructed Harrison's claim while favouring the lunar distance method", "D. He was the official who recommended awarding Harrison the full prize"], answer: "C", explanation: "The passage states Maskelyne 'dismissed Harrison's instruments' and 'arranged for the official trials to be conducted in circumstances that he controlled'." },
      { id: 7, type: "tfng", q: "The chronometer had no significant impact on global commerce or warfare beyond solving the longitude problem.", answer: "FALSE", explanation: "The passage says the chronometer 'fundamentally transformed the nature of global commerce, warfare, and exploration'." },
      { id: 8, type: "short_answer", q: "How much money did the Board of Longitude offer as a prize for solving the longitude problem?", answer: "£20,000", acceptedAnswers: ["£20,000", "20,000", "20000", "£20000"], explanation: "The passage states the prize was '£20,000 — equivalent to several million pounds in contemporary terms'." },
      { id: 9, type: "sentence_completion", q: "Complete the sentence using NO MORE THAN THREE WORDS from the passage.", sentenceTemplate: "Harrison was compelled to petition _____ directly before Parliament eventually awarded him the full prize.", answer: "King George III", acceptedAnswers: ["king george iii", "king george the third"], explanation: "The passage states 'Harrison was compelled to petition King George III directly'." },
      { id: 10, type: "mcq", q: "What positional error did a one-hour timekeeping mistake cause?", opts: ["A. Over fifty kilometres", "B. Exactly fifteen kilometres", "C. Over one hundred kilometres", "D. Approximately two hundred kilometres"], answer: "C", explanation: "The passage states 'a one-hour error in timekeeping translated to a positional error of over one hundred kilometres'." },
    ],
  },

  {
    id: "biophilic-urbanism",
    title: "Biophilic Urbanism: Designing the Cities of Tomorrow",
    tag: "Academic",
    level: "Band 7–8",
    wordCount: 430,
    text: `Cities have long been conceived in opposition to nature — the concrete and steel of the urban environment contrasted against the organic complexity of the natural world. This dichotomy is increasingly recognised, both by urban planners and public health researchers, as not merely an aesthetic failing but a contributor to measurable physical and psychological harm. The emerging discipline of biophilic urbanism — which seeks to reintegrate natural systems into the design and function of cities — represents one of the most ambitious responses to this recognition.

The theoretical foundation of biophilic urbanism rests on the concept of biophilia, a term coined by the Harvard biologist Edward O. Wilson in his 1984 book of the same name. Wilson proposed that human beings possess an innate, genetically embedded affinity for other living systems — an evolutionary inheritance from the hundreds of thousands of years our ancestors spent embedded in natural environments. The implication for urban design is significant: if humans are neurologically predisposed to respond positively to natural forms, textures, and processes, then incorporating these elements into the built environment should produce measurable wellbeing benefits.

The empirical evidence for these benefits is substantial. Research published in the British Journal of Psychiatry found that residents of urban areas with more green space reported significantly lower rates of anxiety and depression, even after controlling for income and socioeconomic status. Studies of hospital recovery rates have shown that patients with window views of trees or natural landscapes recover faster from surgery and require less pain medication than those facing brick walls or blank windows. In the workplace, access to daylight and vegetation has been linked to significant improvements in concentration, productivity, and absenteeism rates.

Translating these findings into practice has led to a diverse range of architectural and urban planning interventions. Singapore is frequently cited as the world's leading example of biophilic urbanism in practice: the city-state has mandated that for every square metre of green space displaced by new construction, an equivalent area must be replaced at height — on rooftops, terraces, and building facades. The result is a city whose skyline is draped in cascading vegetation, earning it the designation of a "City in a Garden." In Europe, cities such as Oslo and Amsterdam are embedding biodiversity requirements into planning policy, requiring new developments to include native species planting, green roofs, and permeable surfaces that support urban water cycles.

Critics of biophilic urbanism raise practical objections. Green infrastructure has significant ongoing maintenance costs — a living wall in a temperate climate may require regular irrigation, specialist horticultural expertise, and periodic replacement of dead vegetation. In cities where housing is already severely unaffordable, the additional cost of biophilic design may be passed on to residents in the form of higher rents or property prices, potentially excluding the very communities most in need of access to green space. These tensions suggest that while the principles of biophilic urbanism are sound, their equitable implementation requires careful policy design rather than purely market-led approaches.`,
    questions: [
      { id: 1, type: "mcq", q: "According to the passage, what does the concept of biophilia propose?", opts: ["A. That cities are fundamentally incompatible with natural environments", "B. That humans have a genetically inherited affinity for other living systems", "C. That urban areas can never replicate the conditions of the natural world", "D. That green spaces in cities reduce carbon emissions significantly"], answer: "B", explanation: "Wilson proposed 'that human beings possess an innate, genetically embedded affinity for other living systems'." },
      { id: 2, type: "tfng", q: "Edward O. Wilson's book on biophilia was published in 1994.", answer: "FALSE", explanation: "The passage states the book was published 'in 1984', not 1994." },
      { id: 3, type: "tfng", q: "Research has shown that hospital patients with views of nature require less pain medication after surgery.", answer: "TRUE", explanation: "The passage states patients with natural views 'recover faster from surgery and require less pain medication than those facing brick walls or blank windows'." },
      { id: 4, type: "mcq", q: "How has Singapore implemented biophilic urbanism, according to the passage?", opts: ["A. By banning all new construction that permanently removes green space", "B. By requiring that displaced green space be replaced with equivalent area at height", "C. By mandating native species gardens in all residential properties", "D. By creating a national fund to subsidise green roofing for private developers"], answer: "B", explanation: "Singapore mandated that 'for every square metre of green space displaced by new construction, an equivalent area must be replaced at height'." },
      { id: 5, type: "tfng", q: "The passage suggests that biophilic design is equally accessible and affordable for all urban communities.", answer: "FALSE", explanation: "Critics note the costs 'may be passed on to residents', potentially 'excluding the very communities most in need of access to green space'." },
      { id: 6, type: "mcq", q: "What concern do critics of biophilic urbanism raise regarding its implementation?", opts: ["A. That green infrastructure causes structural instability in tall buildings", "B. That biodiversity requirements reduce the aesthetic value of city architecture", "C. That costs may be passed to residents, making housing even less affordable", "D. That living walls are completely ineffective in temperate climates"], answer: "C", explanation: "Critics argue additional costs 'may be passed on to residents in the form of higher rents or property prices', worsening affordability." },
      { id: 7, type: "mcq", q: "What is the primary purpose of the final paragraph?", opts: ["A. To argue that biophilic urbanism should be abandoned in favour of conventional design", "B. To acknowledge practical limitations requiring policy solutions for equitable implementation", "C. To present evidence that green infrastructure maintenance costs are steadily declining", "D. To suggest that higher property prices ultimately benefit urban economies"], answer: "B", explanation: "The paragraph presents critics' practical concerns and concludes that 'equitable implementation requires careful policy design', balancing principles with reality." },
      { id: 8, type: "short_answer", q: "In what year did Edward O. Wilson publish his book introducing the concept of biophilia?", answer: "1984", acceptedAnswers: ["1984"], explanation: "The passage states Wilson coined the term 'in his 1984 book of the same name'." },
      { id: 9, type: "tfng", q: "Oslo and Amsterdam have embedded biodiversity requirements into new development planning policy.", answer: "TRUE", explanation: "The passage states these cities 'are embedding biodiversity requirements into planning policy, requiring new developments to include native species planting, green roofs, and permeable surfaces'." },
      { id: 10, type: "ynng", q: "The writer believes the principles of biophilic urbanism are fundamentally sound, but their fair implementation requires deliberate policy rather than market forces alone.", answer: "YES", explanation: "The final sentence explicitly states 'the principles of biophilic urbanism are sound' but 'equitable implementation requires careful policy design rather than purely market-led approaches'." },
    ],
  },

  // ─── General Training Passages ──────────────────────────────────────────────

  {
    id: "bicycle-couriers",
    title: "The History of Bicycle Couriers",
    tag: "History",
    level: "General Training",
    wordCount: 320,
    text: `Before mobile phones and email became common, many businesses depended on bicycle couriers to deliver important documents quickly across busy cities. In large financial centres such as London and New York, bicycle messengers transported contracts, legal papers, and banking records between offices throughout the day. Companies preferred bicycles because riders moved faster than cars in areas with heavy traffic congestion.

The profession became increasingly popular during the 1980s. Many young workers found the job attractive because it offered flexible schedules and required little formal education. Couriers often worked independently and received payment according to the number of deliveries completed each day. Experienced riders learned the fastest routes through crowded streets and developed strong physical endurance.

However, the work involved serious risks. Bicycle couriers frequently travelled in dangerous weather conditions and shared narrow roads with buses, taxis, and delivery trucks. Several city governments introduced safety regulations after accidents involving cyclists increased. Riders in many regions must now wear helmets and reflective clothing while working.

Technology later reduced demand for traditional courier services. Email and digital signatures replaced many paper documents previously delivered by hand. Despite this decline, bicycle courier companies still operate in large urban areas where businesses require immediate transportation of small packages. Some modern services also deliver restaurant meals and online shopping orders directly to customers.

Environmental concerns have recently renewed interest in bicycle deliveries. Unlike cars or motorcycles, bicycles produce no air pollution and require little parking space. Several city councils now support cycling infrastructure projects to encourage businesses to use environmentally friendly transport options. As urban populations continue to grow, some experts believe bicycle couriers will remain an important part of city life.`,
    questions: [
      { id: 1001, type: "tfng", q: "Bicycle couriers were used to deliver documents before email became widely available.", answer: "TRUE", explanation: "The passage opens by stating that before mobile phones and email, businesses depended on bicycle couriers." },
      { id: 1002, type: "tfng", q: "Companies chose bicycles mainly because they were cheaper than cars.", answer: "NOT GIVEN", explanation: "The passage says bicycles were preferred because riders were faster in traffic; cost is never mentioned." },
      { id: 1003, type: "tfng", q: "The job of a bicycle courier required a high level of formal education.", answer: "FALSE", explanation: "The passage states the job required little formal education." },
      { id: 1004, type: "tfng", q: "Couriers were usually paid a fixed monthly salary.", answer: "FALSE", explanation: "Couriers received payment according to the number of deliveries completed each day, not a fixed salary." },
      { id: 1005, type: "tfng", q: "Safety regulations for cyclists were introduced after accidents increased.", answer: "TRUE", explanation: "Several city governments introduced safety regulations after accidents involving cyclists increased." },
      { id: 1006, type: "tfng", q: "Bicycle couriers earned more money than office workers.", answer: "NOT GIVEN", explanation: "The passage does not compare courier earnings with those of office workers." },
      { id: 1007, type: "tfng", q: "Email and digital signatures reduced the need for paper document delivery.", answer: "TRUE", explanation: "The passage states email and digital signatures replaced many paper documents previously delivered by hand." },
      { id: 1008, type: "tfng", q: "All bicycle courier companies have now closed down.", answer: "FALSE", explanation: "The passage says courier companies still operate in large urban areas." },
      { id: 1009, type: "mcq", q: "According to the passage, why did companies prefer bicycle couriers over cars?", opts: ["A. Bicycles caused less pollution", "B. Riders were faster in heavy traffic", "C. Bicycles were easier to repair", "D. Drivers were difficult to hire"], answer: "B", explanation: "Companies preferred bicycles because riders moved faster than cars in heavy traffic congestion." },
      { id: 1010, type: "mcq", q: "The profession of bicycle courier became increasingly popular during:", opts: ["A. the 1960s", "B. the 1970s", "C. the 1980s", "D. the 1990s"], answer: "C", explanation: "The passage states the profession became increasingly popular during the 1980s." },
      { id: 1011, type: "mcq", q: "What made the courier job attractive to many young workers?", opts: ["A. High pay and regular bonuses", "B. Flexible schedules and little need for formal education", "C. Safe working conditions", "D. Clear opportunities for promotion"], answer: "B", explanation: "The job offered flexible schedules and required little formal education." },
      { id: 1012, type: "mcq", q: "How did experienced riders differ from new ones?", opts: ["A. They worked far fewer hours", "B. They knew the fastest routes and had strong endurance", "C. They used motorcycles instead", "D. They delivered only legal papers"], answer: "B", explanation: "Experienced riders learned the fastest routes and developed strong physical endurance." },
      { id: 1013, type: "mcq", q: "What did several city governments do in response to rising cyclist accidents?", opts: ["A. Banned bicycle couriers", "B. Built separate cycle roads", "C. Introduced safety regulations", "D. Reduced city traffic"], answer: "C", explanation: "Several city governments introduced safety regulations after accidents increased." },
      { id: 1014, type: "mcq", q: "What replaced many paper documents once delivered by hand?", opts: ["A. Telephones", "B. Fax machines", "C. Postal services", "D. Email and digital signatures"], answer: "D", explanation: "Email and digital signatures replaced many paper documents previously delivered by hand." },
      { id: 1015, type: "mcq", q: "What kind of deliveries do some modern courier services handle?", opts: ["A. Furniture and large packages", "B. Restaurant meals and online shopping orders", "C. Industrial equipment", "D. International freight"], answer: "B", explanation: "Some modern services deliver restaurant meals and online shopping orders directly to customers." },
      { id: 1016, type: "mcq", q: "According to the passage, one environmental advantage of bicycles is that they:", opts: ["A. travel very long distances", "B. produce no air pollution", "C. carry extremely heavy loads", "D. need expensive fuel"], answer: "B", explanation: "Unlike cars or motorcycles, bicycles produce no air pollution." },
      { id: 1017, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "In large financial centres, bicycle messengers transported contracts, legal papers, and _______ between offices.", answer: "banking records", acceptedAnswers: ["banking records"], explanation: "Messengers transported contracts, legal papers, and banking records between offices." },
      { id: 1018, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "The profession of bicycle courier became increasingly popular during the _______.", answer: "1980s", acceptedAnswers: ["1980s"], explanation: "The passage states the profession became popular during the 1980s." },
      { id: 1019, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Couriers received payment according to the number of _______ completed each day.", answer: "deliveries", acceptedAnswers: ["deliveries"], explanation: "Payment depended on the number of deliveries completed each day." },
      { id: 1020, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Bicycle couriers frequently travelled in dangerous _______ conditions.", answer: "weather", acceptedAnswers: ["weather"], explanation: "Couriers frequently travelled in dangerous weather conditions." },
      { id: 1021, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Riders in many regions must now wear helmets and _______ clothing while working.", answer: "reflective", acceptedAnswers: ["reflective"], explanation: "Riders must now wear helmets and reflective clothing." },
      { id: 1022, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Unlike cars or motorcycles, bicycles produce no _______.", answer: "air pollution", acceptedAnswers: ["air pollution", "pollution"], explanation: "Bicycles produce no air pollution." },
      { id: 1023, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Several city councils now support cycling _______ projects.", answer: "infrastructure", acceptedAnswers: ["infrastructure"], explanation: "City councils support cycling infrastructure projects." },
      { id: 1024, type: "short_answer", q: "Which two cities are mentioned as large financial centres?", answer: "London and New York", acceptedAnswers: ["london and new york", "new york and london"], explanation: "London and New York are named as large financial centres." },
      { id: 1025, type: "short_answer", q: "What did couriers develop in addition to learning the fastest routes?", answer: "physical endurance", acceptedAnswers: ["physical endurance", "strong physical endurance", "endurance"], explanation: "Experienced riders developed strong physical endurance." },
      { id: 1026, type: "short_answer", q: "What must riders in many regions now wear, besides reflective clothing?", answer: "helmets", acceptedAnswers: ["helmets", "a helmet", "helmet"], explanation: "Riders must now wear helmets and reflective clothing." },
      { id: 1027, type: "short_answer", q: "What has recently renewed interest in bicycle deliveries?", answer: "environmental concerns", acceptedAnswers: ["environmental concerns", "the environment", "concern for the environment"], explanation: "Environmental concerns have renewed interest in bicycle deliveries." },
      { id: 1028, type: "short_answer", q: "What do bicycles require little of, compared with cars?", answer: "parking space", acceptedAnswers: ["parking space", "space", "parking"], explanation: "Bicycles require little parking space." },
      { id: 1029, type: "short_answer", q: "Who do some experts believe will remain an important part of city life?", answer: "bicycle couriers", acceptedAnswers: ["bicycle couriers", "couriers"], explanation: "Some experts believe bicycle couriers will remain important to city life." },
      { id: 1030, type: "short_answer", q: "What kind of vehicles did couriers share narrow roads with, besides buses and taxis?", answer: "delivery trucks", acceptedAnswers: ["delivery trucks", "trucks"], explanation: "Couriers shared narrow roads with buses, taxis, and delivery trucks." },
    ],
  },

  {
    id: "public-parks",
    title: "The Development of Public Parks",
    tag: "Urban Life",
    level: "General Training",
    wordCount: 370,
    text: `Public parks play an important role in modern cities by providing open spaces where residents relax, exercise, and spend time with family members. Although parks are now common in urban areas around the world, the idea of creating public green spaces developed gradually over several centuries.

During the Industrial Revolution in Europe, factories expanded rapidly and cities became heavily crowded. Workers often lived in unhealthy conditions with little access to clean air or outdoor recreation. Social reformers argued that public parks would improve both physical and mental health among city residents. As a result, governments and wealthy landowners began supporting the construction of large parks in urban centres.

One famous example is Central Park in New York City, which opened in the nineteenth century. Designers carefully planned walking paths, lakes, gardens, and sports facilities to create a peaceful environment separate from busy streets. Similar projects soon appeared in other major cities across Europe and North America.

Public parks also became important locations for cultural activities and community events. Concerts, festivals, and political gatherings often took place in open green spaces because they allowed large numbers of people to meet safely. In some countries, parks included museums, libraries, and public art displays to encourage education and tourism.

Today, city planners continue to expand and modernize public parks. Many parks now contain cycling tracks, outdoor gyms, and playgrounds designed for different age groups. Environmental experts also emphasize the importance of green spaces in reducing air pollution and controlling urban temperatures. Trees and plants absorb carbon dioxide and provide habitats for birds and insects within crowded cities.

Despite these benefits, maintaining public parks requires significant financial investment. Local governments must pay for landscaping, security, waste collection, and repair work. Some cities struggle to protect green spaces because of increasing demand for housing and commercial development. Nevertheless, many residents strongly support preserving public parks for future generations.`,
    questions: [
      { id: 2001, type: "tfng", q: "The concept of public parks developed quickly within a single decade.", answer: "FALSE", explanation: "The idea developed gradually over several centuries, not quickly within one decade." },
      { id: 2002, type: "tfng", q: "During the Industrial Revolution, European cities became overcrowded.", answer: "TRUE", explanation: "Factories expanded rapidly and cities became heavily crowded." },
      { id: 2003, type: "tfng", q: "Social reformers believed parks could improve people's health.", answer: "TRUE", explanation: "Social reformers argued parks would improve physical and mental health." },
      { id: 2004, type: "tfng", q: "Central Park was the first public park ever created.", answer: "NOT GIVEN", explanation: "Central Park is given as a famous example; the passage never claims it was the first." },
      { id: 2005, type: "tfng", q: "Central Park opened in the twentieth century.", answer: "FALSE", explanation: "Central Park opened in the nineteenth century." },
      { id: 2006, type: "tfng", q: "Parks were sometimes used for political gatherings.", answer: "TRUE", explanation: "Concerts, festivals, and political gatherings often took place in green spaces." },
      { id: 2007, type: "tfng", q: "All public parks contain museums and libraries.", answer: "FALSE", explanation: "Only in some countries did parks include museums and libraries." },
      { id: 2008, type: "tfng", q: "Maintaining public parks is expensive for local governments.", answer: "TRUE", explanation: "Maintaining parks requires significant financial investment by local governments." },
      { id: 2009, type: "mcq", q: "Why did cities become heavily crowded during the Industrial Revolution?", opts: ["A. Parks were closed", "B. Factories expanded rapidly", "C. Housing was very cheap", "D. Transport improved greatly"], answer: "B", explanation: "Factories expanded rapidly, and cities became heavily crowded." },
      { id: 2010, type: "mcq", q: "Who began supporting the construction of large parks?", opts: ["A. Factory workers", "B. Tourists", "C. Governments and wealthy landowners", "D. Sports clubs"], answer: "C", explanation: "Governments and wealthy landowners began supporting park construction." },
      { id: 2011, type: "mcq", q: "What did the designers of Central Park carefully plan?", opts: ["A. Factories and offices", "B. Walking paths, lakes, gardens and sports facilities", "C. Railway lines", "D. Shopping centres"], answer: "B", explanation: "Designers planned walking paths, lakes, gardens, and sports facilities." },
      { id: 2012, type: "mcq", q: "Why were parks suitable for concerts and festivals?", opts: ["A. They had no rules", "B. They were always free of charge", "C. They allowed large numbers of people to meet safely", "D. They were near city centres"], answer: "C", explanation: "Open green spaces allowed large numbers of people to meet safely." },
      { id: 2013, type: "mcq", q: "What do many modern parks now contain?", opts: ["A. Factories", "B. Hospitals", "C. Car parks", "D. Cycling tracks, outdoor gyms and playgrounds"], answer: "D", explanation: "Many parks now contain cycling tracks, outdoor gyms, and playgrounds." },
      { id: 2014, type: "mcq", q: "According to the passage, trees and plants in parks help by:", opts: ["A. increasing temperatures", "B. absorbing carbon dioxide", "C. producing noise", "D. blocking all sunlight"], answer: "B", explanation: "Trees and plants absorb carbon dioxide within crowded cities." },
      { id: 2015, type: "mcq", q: "What must local governments pay for to maintain parks?", opts: ["A. Advertising campaigns", "B. New factories", "C. Landscaping, security, waste collection and repair work", "D. Public transport"], answer: "C", explanation: "Local governments pay for landscaping, security, waste collection, and repair work." },
      { id: 2016, type: "mcq", q: "Why do some cities struggle to protect green spaces?", opts: ["A. Lack of visitors", "B. Increasing demand for housing and commercial development", "C. Bad weather", "D. Falling populations"], answer: "B", explanation: "Some cities struggle because of increasing demand for housing and commercial development." },
      { id: 2017, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "During the Industrial Revolution, workers often lived in unhealthy conditions with little access to clean air or outdoor _______.", answer: "recreation", acceptedAnswers: ["recreation"], explanation: "Workers had little access to clean air or outdoor recreation." },
      { id: 2018, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "One famous example is _______ in New York City, which opened in the nineteenth century.", answer: "Central Park", acceptedAnswers: ["central park"], explanation: "Central Park is the famous example given." },
      { id: 2019, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Concerts, festivals, and political _______ often took place in open green spaces.", answer: "gatherings", acceptedAnswers: ["gatherings"], explanation: "Political gatherings took place in open green spaces." },
      { id: 2020, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Environmental experts emphasize the importance of green spaces in reducing air _______.", answer: "pollution", acceptedAnswers: ["pollution"], explanation: "Green spaces help reduce air pollution." },
      { id: 2021, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Trees and plants absorb carbon dioxide and provide _______ for birds and insects.", answer: "habitats", acceptedAnswers: ["habitats"], explanation: "Trees and plants provide habitats for birds and insects." },
      { id: 2022, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Many parks now contain cycling tracks, outdoor gyms, and _______ designed for different age groups.", answer: "playgrounds", acceptedAnswers: ["playgrounds"], explanation: "Parks now contain playgrounds designed for different age groups." },
      { id: 2023, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Many residents strongly support preserving public parks for future _______.", answer: "generations", acceptedAnswers: ["generations"], explanation: "Residents support preserving parks for future generations." },
      { id: 2024, type: "short_answer", q: "What did social reformers argue public parks would improve, besides physical health?", answer: "mental health", acceptedAnswers: ["mental health"], explanation: "Reformers argued parks would improve both physical and mental health." },
      { id: 2025, type: "short_answer", q: "In which city did Central Park open?", answer: "New York City", acceptedAnswers: ["new york city", "new york"], explanation: "Central Park opened in New York City." },
      { id: 2026, type: "short_answer", q: "Besides Europe, in which region did similar park projects appear?", answer: "North America", acceptedAnswers: ["north america"], explanation: "Similar projects appeared across Europe and North America." },
      { id: 2027, type: "short_answer", q: "What do green spaces help control, in addition to reducing air pollution?", answer: "urban temperatures", acceptedAnswers: ["urban temperatures", "temperatures", "temperature"], explanation: "Green spaces help in controlling urban temperatures." },
      { id: 2028, type: "short_answer", q: "What gas do trees and plants absorb?", answer: "carbon dioxide", acceptedAnswers: ["carbon dioxide", "co2"], explanation: "Trees and plants absorb carbon dioxide." },
      { id: 2029, type: "short_answer", q: "What kind of investment does maintaining public parks require?", answer: "financial", acceptedAnswers: ["financial", "financial investment", "significant financial investment"], explanation: "Maintaining parks requires significant financial investment." },
      { id: 2030, type: "short_answer", q: "What two types of development create demand that threatens green spaces?", answer: "housing and commercial", acceptedAnswers: ["housing and commercial", "housing and commercial development", "commercial and housing"], explanation: "Demand for housing and commercial development threatens green spaces." },
    ],
  },

  {
    id: "remote-working",
    title: "Remote Working and Modern Employment",
    tag: "Employment",
    level: "General Training",
    wordCount: 360,
    text: `Remote working became far more common after advances in internet technology allowed employees to communicate from home. While some companies experimented with flexible working arrangements in earlier decades, the global pandemic during the early 2020s forced millions of workers to perform their duties outside traditional offices.

Many employees quickly recognized advantages associated with remote work. Travelling to offices often consumes several hours each week, especially in large cities with heavy traffic. Working from home reduced commuting expenses and allowed workers to spend more time with family members. Some employees also reported higher productivity because they experienced fewer interruptions compared with open office environments.

Businesses discovered financial benefits as well. Companies reduced spending on office rent, electricity, and maintenance costs when fewer workers occupied physical workplaces. International firms also expanded recruitment opportunities because they could hire skilled employees living in different countries or regions.

However, remote working created several challenges. Some workers struggled to separate professional responsibilities from personal life, particularly when living in small apartments or shared accommodation. Others reported feelings of isolation because they missed daily interaction with colleagues. Managers also faced difficulties supervising large teams remotely and maintaining effective communication between departments.

Technology companies responded by developing advanced online meeting platforms and collaboration tools. Video conferencing, cloud storage systems, and instant messaging applications became essential parts of modern business operations. Training programs helped employees improve digital communication skills and cybersecurity awareness.

Experts disagree about the future of remote work. Some believe traditional offices will remain important for teamwork and innovation, while others predict hybrid systems combining office and home working will become standard practice. Many organizations already allow employees to choose flexible schedules depending on job requirements. Regardless of future trends, remote working has permanently changed how businesses operate in many industries.`,
    questions: [
      { id: 3001, type: "tfng", q: "Flexible working arrangements existed before the early 2020s.", answer: "TRUE", explanation: "Some companies experimented with flexible working arrangements in earlier decades." },
      { id: 3002, type: "tfng", q: "The pandemic of the early 2020s caused millions of workers to work outside offices.", answer: "TRUE", explanation: "The global pandemic forced millions of workers to perform duties outside traditional offices." },
      { id: 3003, type: "tfng", q: "All employees found that working from home increased their productivity.", answer: "FALSE", explanation: "Only some employees reported higher productivity, not all." },
      { id: 3004, type: "tfng", q: "Companies spent more money on office rent during the rise of remote work.", answer: "FALSE", explanation: "Companies reduced spending on office rent when fewer workers used workplaces." },
      { id: 3005, type: "tfng", q: "Remote working made it easier for managers to supervise large teams.", answer: "FALSE", explanation: "Managers faced difficulties supervising large teams remotely." },
      { id: 3006, type: "ynng", q: "Traditional offices are no longer useful for any business activity.", answer: "NO", explanation: "Some experts believe traditional offices remain important for teamwork and innovation." },
      { id: 3007, type: "ynng", q: "Experts hold the same opinion about the future of remote work.", answer: "NO", explanation: "The passage states that experts disagree about the future of remote work." },
      { id: 3008, type: "tfng", q: "Remote working has permanently changed business operations in many industries.", answer: "TRUE", explanation: "Remote working has permanently changed how businesses operate in many industries." },
      { id: 3009, type: "mcq", q: "What allowed employees to communicate from home?", opts: ["A. Cheaper housing", "B. Advances in internet technology", "C. New government laws", "D. Larger offices"], answer: "B", explanation: "Advances in internet technology allowed employees to communicate from home." },
      { id: 3010, type: "mcq", q: "Why does commuting consume several hours each week?", opts: ["A. Workers travel slowly", "B. Offices open late", "C. Large cities have heavy traffic", "D. Public transport is rare"], answer: "C", explanation: "Travelling to offices consumes hours, especially in large cities with heavy traffic." },
      { id: 3011, type: "mcq", q: "One reported advantage of working from home was:", opts: ["A. higher office rent", "B. fewer interruptions than in open offices", "C. more frequent meetings", "D. longer working hours"], answer: "B", explanation: "Some employees reported fewer interruptions than in open office environments." },
      { id: 3012, type: "mcq", q: "How did international firms benefit from remote work?", opts: ["A. They closed all offices", "B. They paid lower taxes", "C. They could hire skilled employees in different countries", "D. They reduced salaries"], answer: "C", explanation: "International firms could hire skilled employees living in different countries or regions." },
      { id: 3013, type: "mcq", q: "Which workers struggled most to separate work and personal life?", opts: ["A. Those in large houses", "B. Those living in small apartments or shared accommodation", "C. Senior managers", "D. Part-time staff"], answer: "B", explanation: "Workers in small apartments or shared accommodation struggled to separate work and personal life." },
      { id: 3014, type: "mcq", q: "What did some remote workers report feeling?", opts: ["A. Excitement", "B. Isolation", "C. Boredom with travel", "D. Increased income"], answer: "B", explanation: "Some workers reported feelings of isolation." },
      { id: 3015, type: "mcq", q: "What became essential parts of modern business operations?", opts: ["A. Printed documents", "B. Office furniture", "C. Company cars", "D. Video conferencing, cloud storage and instant messaging"], answer: "D", explanation: "Video conferencing, cloud storage, and instant messaging became essential." },
      { id: 3016, type: "mcq", q: "According to the passage, experts:", opts: ["A. agree remote work will end", "B. disagree about the future of remote work", "C. believe all offices will close", "D. recommend banning home working"], answer: "B", explanation: "Experts disagree about the future of remote work." },
      { id: 3017, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Working from home reduced commuting expenses and allowed workers to spend more time with _______.", answer: "family members", acceptedAnswers: ["family members", "family", "their family"], explanation: "Workers could spend more time with family members." },
      { id: 3018, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Companies reduced spending on office rent, electricity, and _______ costs.", answer: "maintenance", acceptedAnswers: ["maintenance"], explanation: "Companies reduced spending on rent, electricity, and maintenance costs." },
      { id: 3019, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Some workers reported feelings of _______ because they missed daily interaction with colleagues.", answer: "isolation", acceptedAnswers: ["isolation"], explanation: "Workers reported feelings of isolation." },
      { id: 3020, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Training programs helped employees improve digital communication skills and _______ awareness.", answer: "cybersecurity", acceptedAnswers: ["cybersecurity", "cyber security"], explanation: "Training improved digital communication skills and cybersecurity awareness." },
      { id: 3021, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Some experts believe traditional offices will remain important for teamwork and _______.", answer: "innovation", acceptedAnswers: ["innovation"], explanation: "Offices remain important for teamwork and innovation." },
      { id: 3022, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Many organizations already allow employees to choose flexible _______ depending on job requirements.", answer: "schedules", acceptedAnswers: ["schedules"], explanation: "Organizations allow employees to choose flexible schedules." },
      { id: 3023, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Managers faced difficulties maintaining effective communication between _______.", answer: "departments", acceptedAnswers: ["departments"], explanation: "Managers struggled to maintain communication between departments." },
      { id: 3024, type: "short_answer", q: "When did the global pandemic occur, according to the passage?", answer: "the early 2020s", acceptedAnswers: ["early 2020s", "the early 2020s", "2020s"], explanation: "The global pandemic occurred during the early 2020s." },
      { id: 3025, type: "short_answer", q: "Name one cost businesses reduced when fewer workers used physical workplaces.", answer: "office rent", acceptedAnswers: ["office rent", "rent", "electricity", "maintenance", "maintenance costs"], explanation: "Businesses reduced office rent, electricity, and maintenance costs." },
      { id: 3026, type: "short_answer", q: "What did technology companies develop to support remote work, besides online meeting platforms?", answer: "collaboration tools", acceptedAnswers: ["collaboration tools", "online meeting platforms and collaboration tools"], explanation: "Technology companies developed online meeting platforms and collaboration tools." },
      { id: 3027, type: "short_answer", q: "What kind of systems combine office and home working?", answer: "hybrid systems", acceptedAnswers: ["hybrid systems", "hybrid"], explanation: "Hybrid systems combine office and home working." },
      { id: 3028, type: "short_answer", q: "What did some workers miss when working remotely?", answer: "interaction with colleagues", acceptedAnswers: ["interaction with colleagues", "daily interaction with colleagues", "colleagues"], explanation: "Workers missed daily interaction with colleagues." },
      { id: 3029, type: "short_answer", q: "What type of skills did training programs help employees improve?", answer: "digital communication", acceptedAnswers: ["digital communication", "digital communication skills", "communication"], explanation: "Training helped improve digital communication skills." },
      { id: 3030, type: "short_answer", q: "What has remote working permanently changed?", answer: "how businesses operate", acceptedAnswers: ["how businesses operate", "business operations", "the way businesses operate"], explanation: "Remote working has permanently changed how businesses operate." },
    ],
  },

  {
    id: "farmers-markets",
    title: "The Growth of Farmers' Markets",
    tag: "Lifestyle",
    level: "General Training",
    wordCount: 365,
    text: `Farmers' markets have become increasingly popular in many countries during recent years. These markets allow local farmers and food producers to sell products directly to consumers without large supermarket chains acting as intermediaries. Customers often purchase fresh vegetables, fruit, bread, cheese, honey, and handmade goods at weekly outdoor markets.

Historically, local markets served as essential centres of trade in towns and villages. Farmers travelled short distances to sell crops and livestock directly to nearby communities. However, the expansion of supermarkets during the twentieth century reduced the importance of traditional local markets in many regions.

Interest in farmers' markets returned as consumers became more concerned about food quality and environmental sustainability. Supporters argue that locally produced food often remains fresher because it travels shorter distances before reaching customers. Reducing transportation also decreases fuel consumption and environmental pollution.

Many shoppers appreciate opportunities to speak directly with producers about farming methods and product ingredients. Some consumers prefer purchasing organic food grown without certain chemicals or artificial fertilizers. Farmers' markets often promote seasonal products, encouraging people to eat foods naturally available during different times of the year.

For small farmers, direct sales provide important economic advantages. Producers usually earn higher profits because they avoid paying fees to large distribution companies or supermarkets. Farmers also build stronger relationships with local communities and gain immediate feedback from customers.

Despite their popularity, farmers' markets face several limitations. Products sometimes cost more than supermarket alternatives because small farms produce lower quantities of food. Weather conditions also affect outdoor markets, reducing customer numbers during extremely hot or rainy periods. In addition, not all consumers have easy access to local markets, particularly in heavily urbanized areas.

Governments and environmental organizations continue supporting local food initiatives through educational campaigns and financial assistance programs. Many experts believe farmers' markets will remain important as consumers seek healthier diets and stronger connections with local agriculture.`,
    questions: [
      { id: 4001, type: "tfng", q: "Farmers' markets allow producers to sell directly to consumers.", answer: "TRUE", explanation: "These markets allow local farmers and producers to sell products directly to consumers." },
      { id: 4002, type: "tfng", q: "Supermarket chains act as intermediaries at farmers' markets.", answer: "FALSE", explanation: "Farmers' markets operate without large supermarket chains acting as intermediaries." },
      { id: 4003, type: "tfng", q: "The growth of supermarkets in the twentieth century increased the importance of local markets.", answer: "FALSE", explanation: "The expansion of supermarkets reduced the importance of traditional local markets." },
      { id: 4004, type: "ynng", q: "Locally produced food is fresher because it travels shorter distances.", answer: "YES", explanation: "Supporters argue locally produced food remains fresher because it travels shorter distances." },
      { id: 4005, type: "tfng", q: "All consumers can easily reach a farmers' market.", answer: "FALSE", explanation: "Not all consumers have easy access, particularly in heavily urbanized areas." },
      { id: 4006, type: "tfng", q: "Bad weather can reduce the number of customers at outdoor markets.", answer: "TRUE", explanation: "Weather conditions reduce customer numbers during extremely hot or rainy periods." },
      { id: 4007, type: "tfng", q: "Farmers' market products are always cheaper than supermarket products.", answer: "FALSE", explanation: "Products sometimes cost more than supermarket alternatives." },
      { id: 4008, type: "ynng", q: "Farmers' markets will continue to be important in the future.", answer: "YES", explanation: "Many experts believe farmers' markets will remain important." },
      { id: 4009, type: "mcq", q: "What can customers buy at farmers' markets?", opts: ["A. Electronic goods", "B. Fresh vegetables, fruit, bread and honey", "C. Furniture", "D. Only clothing"], answer: "B", explanation: "Customers purchase fresh vegetables, fruit, bread, cheese, honey, and handmade goods." },
      { id: 4010, type: "mcq", q: "How often are the outdoor markets described as taking place?", opts: ["A. Daily", "B. Weekly", "C. Monthly", "D. Yearly"], answer: "B", explanation: "The passage describes weekly outdoor markets." },
      { id: 4011, type: "mcq", q: "What reduced the importance of traditional local markets?", opts: ["A. War", "B. Poor harvests", "C. The expansion of supermarkets in the twentieth century", "D. High taxes"], answer: "C", explanation: "The expansion of supermarkets during the twentieth century reduced their importance." },
      { id: 4012, type: "mcq", q: "Why did interest in farmers' markets return?", opts: ["A. Lower prices", "B. Concern about food quality and environmental sustainability", "C. Government orders", "D. A lack of supermarkets"], answer: "B", explanation: "Consumers became more concerned about food quality and environmental sustainability." },
      { id: 4013, type: "mcq", q: "What do some consumers prefer to buy at these markets?", opts: ["A. Frozen food", "B. Imported food", "C. Tinned food", "D. Organic food grown without certain chemicals"], answer: "D", explanation: "Some consumers prefer organic food grown without certain chemicals or artificial fertilizers." },
      { id: 4014, type: "mcq", q: "Why do small farmers usually earn higher profits through direct sales?", opts: ["A. They sell far more food", "B. They avoid paying fees to distributors and supermarkets", "C. They raise prices freely", "D. They receive subsidies"], answer: "B", explanation: "Producers avoid paying fees to large distribution companies or supermarkets." },
      { id: 4015, type: "mcq", q: "Why do farmers' market products sometimes cost more?", opts: ["A. They are imported", "B. Small farms produce lower quantities of food", "C. They are taxed heavily", "D. They are all organic"], answer: "B", explanation: "Products cost more because small farms produce lower quantities of food." },
      { id: 4016, type: "mcq", q: "How do governments and environmental organizations support local food?", opts: ["A. By building supermarkets", "B. By banning imports", "C. Through educational campaigns and financial assistance", "D. By lowering all prices"], answer: "C", explanation: "They support local food through educational campaigns and financial assistance programs." },
      { id: 4017, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Historically, local markets served as essential centres of _______ in towns and villages.", answer: "trade", acceptedAnswers: ["trade"], explanation: "Local markets served as essential centres of trade." },
      { id: 4018, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Reducing transportation also decreases fuel consumption and environmental _______.", answer: "pollution", acceptedAnswers: ["pollution"], explanation: "Reducing transportation decreases fuel consumption and environmental pollution." },
      { id: 4019, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Some consumers prefer purchasing _______ food grown without certain chemicals.", answer: "organic", acceptedAnswers: ["organic"], explanation: "Some consumers prefer organic food." },
      { id: 4020, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Farmers' markets often promote _______ products, encouraging people to eat foods naturally available during different times of the year.", answer: "seasonal", acceptedAnswers: ["seasonal"], explanation: "Markets promote seasonal products." },
      { id: 4021, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Producers usually earn higher _______ because they avoid paying fees to large distribution companies.", answer: "profits", acceptedAnswers: ["profits"], explanation: "Producers usually earn higher profits." },
      { id: 4022, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Farmers build stronger relationships with local communities and gain immediate _______ from customers.", answer: "feedback", acceptedAnswers: ["feedback"], explanation: "Farmers gain immediate feedback from customers." },
      { id: 4023, type: "sentence_completion", q: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.", sentenceTemplate: "Not all consumers have easy access to local markets, particularly in heavily _______ areas.", answer: "urbanized", acceptedAnswers: ["urbanized", "urbanised"], explanation: "Access is limited in heavily urbanized areas." },
      { id: 4024, type: "short_answer", q: "Who do farmers' markets allow to sell products directly to consumers?", answer: "local farmers and food producers", acceptedAnswers: ["local farmers and food producers", "local farmers", "farmers and food producers", "farmers"], explanation: "Markets allow local farmers and food producers to sell directly." },
      { id: 4025, type: "short_answer", q: "What did farmers historically travel short distances to sell, besides crops?", answer: "livestock", acceptedAnswers: ["livestock"], explanation: "Farmers travelled short distances to sell crops and livestock." },
      { id: 4026, type: "short_answer", q: "What do shoppers appreciate discussing directly with producers?", answer: "farming methods", acceptedAnswers: ["farming methods", "farming methods and ingredients", "farming methods and product ingredients"], explanation: "Shoppers appreciate discussing farming methods and ingredients with producers." },
      { id: 4027, type: "short_answer", q: "What can extremely hot or rainy weather reduce at outdoor markets?", answer: "customer numbers", acceptedAnswers: ["customer numbers", "customers", "the number of customers"], explanation: "Bad weather reduces customer numbers at outdoor markets." },
      { id: 4028, type: "short_answer", q: "What do producers avoid paying when they sell directly to consumers?", answer: "fees", acceptedAnswers: ["fees"], explanation: "Producers avoid paying fees to large distribution companies or supermarkets." },
      { id: 4029, type: "short_answer", q: "Organic food is grown without certain chemicals and what else?", answer: "artificial fertilizers", acceptedAnswers: ["artificial fertilizers", "artificial fertilisers", "fertilizers", "fertilisers"], explanation: "Organic food is grown without certain chemicals or artificial fertilizers." },
      { id: 4030, type: "short_answer", q: "What do many experts believe will remain important in the future?", answer: "farmers' markets", acceptedAnswers: ["farmers' markets", "farmers markets", "farmer's markets"], explanation: "Many experts believe farmers' markets will remain important." },
    ],
  },

  {
    id: "silk-road",
    title: "The Micro-Economic Dynamics of the Silk Road",
    tag: "Academic",
    level: "Band 8",
    wordCount: 460,
    text: `The Silk Road — a loose network of overland and maritime trade routes connecting China, Central Asia, Persia, the Arabian Peninsula, Africa, and Europe — is commonly imagined as a single highway of continuous commerce. In reality, the Silk Road was an assemblage of overlapping regional routes, each controlled by different political entities, and characterised by a series of relay stations and merchant cities where goods were exchanged, re-packaged, and passed onward rather than transported in their entirety from origin to destination.

This relay structure had profound micro-economic consequences. Merchants rarely completed the entire transcontinental route; instead, goods passed through the hands of multiple intermediaries across different cultural and political zones. A bolt of Chinese silk might be acquired at a Han Dynasty market town, transported by Sogdian merchants across Central Asia to Persia, sold to Arab traders who moved it through the Persian Gulf, and finally distributed by Byzantine or Italian merchants into European luxury markets — each transaction adding a margin of profit and inflating the final price paid by the European consumer many times over. The Sogdians of Central Asia — an Iranian-speaking people centred in the cities of Samarkand and Bukhara — were perhaps the most commercially adept participants in this system, operating a sophisticated network of trading colonies that extended from China to the Byzantine Empire.

Contrary to its romantic image as a route exclusively for silk, the Silk Road carried a far more diverse cargo. Precious metals, glassware, spices, medicines, gemstones, dyes, and paper all travelled the routes in significant quantities. Ideas and technologies moved alongside physical goods: papermaking technology, gunpowder, and the compass all made their westward journey through Silk Road networks, as did Buddhist, Islamic, and Nestorian Christian religious ideas moving in multiple directions simultaneously.

The economics of the Silk Road were inseparable from its political infrastructure. Trade flourished most intensely during periods of political stability and territorial consolidation — the Pax Romana in the west, the Han Dynasty in the east, and above all during the Pax Mongolica of the thirteenth and fourteenth centuries, when the Mongol Empire's control of Eurasia from China to Eastern Europe created unprecedented security and standardisation of commercial practice across the routes. Conversely, the disruption of political order — the collapse of the Han Dynasty, the fragmentation of the Abbasid Caliphate, or the Ottoman Empire's eventual blockage of traditional eastern trade routes — consistently contracted Silk Road commerce and redirected merchant enterprise toward alternative channels.

The long-term economic legacy of the Silk Road is visible in the commercial geography of the modern world. Cities that served as major entrepôts — Samarkand, Bukhara, Kashgar, Hormuz — retain today only shadows of their former commercial prominence. The Ottoman disruption of Silk Road routes played a significant role in motivating the Portuguese and Spanish maritime expeditions of the fifteenth century, as European powers sought direct sea routes to Asian markets. The wealth generated by this maritime redirecting of trade provided the capital that financed the colonisation of the Americas and underwrote the early modern transformation of European economies.`,
    questions: [
      { id: 1, type: "tfng", q: "The Silk Road was a single, continuous overland route connecting China directly to Europe.", answer: "FALSE", explanation: "The passage describes it as 'a loose network of overlapping regional routes', not a single continuous highway." },
      { id: 2, type: "mcq", q: "According to the passage, who were the Sogdians?", opts: ["A. Chinese merchants who controlled the eastern section of the Silk Road", "B. Persian traders who operated primarily from the Arabian Peninsula", "C. An Iranian-speaking people with trading colonies from China to the Byzantine Empire", "D. A nomadic group that provided protection for merchant caravans across Central Asia"], answer: "C", explanation: "The passage describes the Sogdians as 'an Iranian-speaking people centred in Samarkand and Bukhara' operating colonies 'from China to the Byzantine Empire'." },
      { id: 3, type: "tfng", q: "The Silk Road was used almost exclusively for transporting silk between China and Europe.", answer: "FALSE", explanation: "The passage explicitly states the Silk Road 'carried a far more diverse cargo' including metals, spices, medicines, and technologies." },
      { id: 4, type: "mcq", q: "According to the passage, what was a key factor in the flourishing of Silk Road trade?", opts: ["A. The standardisation of currency across all trading regions", "B. The commercial dominance of a single ethnic merchant group", "C. Periods of political stability and territorial consolidation", "D. The development of faster and more efficient transportation technology"], answer: "C", explanation: "The passage states 'trade flourished most intensely during periods of political stability and territorial consolidation', citing the Pax Romana and Pax Mongolica." },
      { id: 5, type: "mcq", q: "What role did the Pax Mongolica play in Silk Road commerce, according to the passage?", opts: ["A. It redirected commerce from overland to maritime trade routes", "B. It created security and standardisation of commercial practice across Eurasian routes", "C. It enabled Chinese merchants to travel directly to European markets for the first time", "D. It caused the decline of major entrepôt cities such as Samarkand"], answer: "B", explanation: "The passage states the Mongol Empire 'created unprecedented security and standardisation of commercial practice across the routes'." },
      { id: 6, type: "tfng", q: "The Ottoman Empire's disruption of Silk Road trade motivated Portuguese and Spanish maritime expeditions.", answer: "TRUE", explanation: "The passage states 'the Ottoman disruption of Silk Road routes played a significant role in motivating the Portuguese and Spanish maritime expeditions of the fifteenth century'." },
      { id: 7, type: "mcq", q: "What does the passage suggest about the long-term economic legacy of the Silk Road?", opts: ["A. Modern global trade routes continue to follow the same paths as the ancient Silk Road", "B. The wealth from redirected maritime trade contributed directly to European colonial expansion", "C. Former Silk Road entrepôt cities remain major commercial centres in the contemporary world", "D. The Silk Road's most significant contribution was the westward transfer of silk production techniques"], answer: "B", explanation: "The passage states the wealth from maritime redirected trade 'financed the colonisation of the Americas and underwrote the early modern transformation of European economies'." },
      { id: 8, type: "short_answer", q: "Which people are described as perhaps the most commercially adept participants in the Silk Road network?", answer: "Sogdians", acceptedAnswers: ["sogdians", "the sogdians"], explanation: "The passage states 'The Sogdians of Central Asia … were perhaps the most commercially adept participants in this system'." },
      { id: 9, type: "ynng", q: "The writer argues that the Ottoman Empire intentionally blocked Silk Road routes in order to damage European economies.", answer: "NOT GIVEN", explanation: "The passage mentions Ottoman blockage but says nothing about intentional harm to European economies — it only describes the effect (motivating maritime expeditions)." },
      { id: 10, type: "sentence_completion", q: "Complete the sentence using NO MORE THAN THREE WORDS from the passage.", sentenceTemplate: "Ideas and technologies also moved along the Silk Road, including papermaking technology, gunpowder, and the _____.", answer: "compass", acceptedAnswers: ["compass"], explanation: "The passage lists 'papermaking technology, gunpowder, and the compass' as technologies that 'made their westward journey through Silk Road networks'." },
    ],
  },
];
