// lib/quranSurahMeta.ts
// Static reference metadata for the 114 surahs of the Quran — used to generate
// SEO titles/descriptions for /quran/[id] pages and sitemap entries WITHOUT a
// network call. This is public-domain factual data (names, ayah counts,
// revelation place) aligned with the alquran.cloud dataset the reader already
// uses at runtime. Counts follow the standard Hafs/Kufan numbering.
//
// NOTE: This file does not modify or replace any existing data source — the
// digital reader still fetches full ayah text/translations from the API. This
// is purely additive metadata for crawlable page titles.

export interface SurahMeta {
  number: number;
  name: string;        // common transliteration
  arabicName: string;  // Arabic script
  ayahs: number;       // number of ayahs (Hafs/Kufan count)
  revelation: "Meccan" | "Medinan";
}

export const SURAH_META: SurahMeta[] = [
  { number: 1,   name: "Al-Fatihah",      arabicName: "الفاتحة",     ayahs: 7,   revelation: "Meccan"  },
  { number: 2,   name: "Al-Baqarah",      arabicName: "البقرة",      ayahs: 286, revelation: "Medinan" },
  { number: 3,   name: "Aal-E-Imran",     arabicName: "آل عمران",    ayahs: 200, revelation: "Medinan" },
  { number: 4,   name: "An-Nisa",         arabicName: "النساء",      ayahs: 176, revelation: "Medinan" },
  { number: 5,   name: "Al-Ma'idah",      arabicName: "المائدة",     ayahs: 120, revelation: "Medinan" },
  { number: 6,   name: "Al-An'am",        arabicName: "الأنعام",     ayahs: 165, revelation: "Meccan"  },
  { number: 7,   name: "Al-A'raf",        arabicName: "الأعراف",     ayahs: 206, revelation: "Meccan"  },
  { number: 8,   name: "Al-Anfal",        arabicName: "الأنفال",     ayahs: 75,  revelation: "Medinan" },
  { number: 9,   name: "At-Tawbah",       arabicName: "التوبة",      ayahs: 129, revelation: "Medinan" },
  { number: 10,  name: "Yunus",           arabicName: "يونس",        ayahs: 109, revelation: "Meccan"  },
  { number: 11,  name: "Hud",             arabicName: "هود",         ayahs: 123, revelation: "Meccan"  },
  { number: 12,  name: "Yusuf",           arabicName: "يوسف",        ayahs: 111, revelation: "Meccan"  },
  { number: 13,  name: "Ar-Ra'd",         arabicName: "الرعد",       ayahs: 43,  revelation: "Medinan" },
  { number: 14,  name: "Ibrahim",         arabicName: "إبراهيم",     ayahs: 52,  revelation: "Meccan"  },
  { number: 15,  name: "Al-Hijr",         arabicName: "الحجر",       ayahs: 99,  revelation: "Meccan"  },
  { number: 16,  name: "An-Nahl",         arabicName: "النحل",       ayahs: 128, revelation: "Meccan"  },
  { number: 17,  name: "Al-Isra",         arabicName: "الإسراء",     ayahs: 111, revelation: "Meccan"  },
  { number: 18,  name: "Al-Kahf",         arabicName: "الكهف",       ayahs: 110, revelation: "Meccan"  },
  { number: 19,  name: "Maryam",          arabicName: "مريم",        ayahs: 98,  revelation: "Meccan"  },
  { number: 20,  name: "Ta-Ha",           arabicName: "طه",          ayahs: 135, revelation: "Meccan"  },
  { number: 21,  name: "Al-Anbiya",       arabicName: "الأنبياء",    ayahs: 112, revelation: "Meccan"  },
  { number: 22,  name: "Al-Hajj",         arabicName: "الحج",        ayahs: 78,  revelation: "Medinan" },
  { number: 23,  name: "Al-Mu'minun",     arabicName: "المؤمنون",    ayahs: 118, revelation: "Meccan"  },
  { number: 24,  name: "An-Nur",          arabicName: "النور",       ayahs: 64,  revelation: "Medinan" },
  { number: 25,  name: "Al-Furqan",       arabicName: "الفرقان",     ayahs: 77,  revelation: "Meccan"  },
  { number: 26,  name: "Ash-Shu'ara",     arabicName: "الشعراء",     ayahs: 227, revelation: "Meccan"  },
  { number: 27,  name: "An-Naml",         arabicName: "النمل",       ayahs: 93,  revelation: "Meccan"  },
  { number: 28,  name: "Al-Qasas",        arabicName: "القصص",       ayahs: 88,  revelation: "Meccan"  },
  { number: 29,  name: "Al-Ankabut",      arabicName: "العنكبوت",    ayahs: 69,  revelation: "Meccan"  },
  { number: 30,  name: "Ar-Rum",          arabicName: "الروم",       ayahs: 60,  revelation: "Meccan"  },
  { number: 31,  name: "Luqman",          arabicName: "لقمان",       ayahs: 34,  revelation: "Meccan"  },
  { number: 32,  name: "As-Sajdah",       arabicName: "السجدة",      ayahs: 30,  revelation: "Meccan"  },
  { number: 33,  name: "Al-Ahzab",        arabicName: "الأحزاب",     ayahs: 73,  revelation: "Medinan" },
  { number: 34,  name: "Saba",            arabicName: "سبأ",         ayahs: 54,  revelation: "Meccan"  },
  { number: 35,  name: "Fatir",           arabicName: "فاطر",        ayahs: 45,  revelation: "Meccan"  },
  { number: 36,  name: "Ya-Sin",          arabicName: "يس",          ayahs: 83,  revelation: "Meccan"  },
  { number: 37,  name: "As-Saffat",       arabicName: "الصافات",     ayahs: 182, revelation: "Meccan"  },
  { number: 38,  name: "Sad",             arabicName: "ص",           ayahs: 88,  revelation: "Meccan"  },
  { number: 39,  name: "Az-Zumar",        arabicName: "الزمر",       ayahs: 75,  revelation: "Meccan"  },
  { number: 40,  name: "Ghafir",          arabicName: "غافر",        ayahs: 85,  revelation: "Meccan"  },
  { number: 41,  name: "Fussilat",        arabicName: "فصلت",        ayahs: 54,  revelation: "Meccan"  },
  { number: 42,  name: "Ash-Shura",       arabicName: "الشورى",      ayahs: 53,  revelation: "Meccan"  },
  { number: 43,  name: "Az-Zukhruf",      arabicName: "الزخرف",      ayahs: 89,  revelation: "Meccan"  },
  { number: 44,  name: "Ad-Dukhan",       arabicName: "الدخان",      ayahs: 59,  revelation: "Meccan"  },
  { number: 45,  name: "Al-Jathiyah",     arabicName: "الجاثية",     ayahs: 37,  revelation: "Meccan"  },
  { number: 46,  name: "Al-Ahqaf",        arabicName: "الأحقاف",     ayahs: 35,  revelation: "Meccan"  },
  { number: 47,  name: "Muhammad",        arabicName: "محمد",        ayahs: 38,  revelation: "Medinan" },
  { number: 48,  name: "Al-Fath",         arabicName: "الفتح",       ayahs: 29,  revelation: "Medinan" },
  { number: 49,  name: "Al-Hujurat",      arabicName: "الحجرات",     ayahs: 18,  revelation: "Medinan" },
  { number: 50,  name: "Qaf",             arabicName: "ق",           ayahs: 45,  revelation: "Meccan"  },
  { number: 51,  name: "Adh-Dhariyat",    arabicName: "الذاريات",    ayahs: 60,  revelation: "Meccan"  },
  { number: 52,  name: "At-Tur",          arabicName: "الطور",       ayahs: 49,  revelation: "Meccan"  },
  { number: 53,  name: "An-Najm",         arabicName: "النجم",       ayahs: 62,  revelation: "Meccan"  },
  { number: 54,  name: "Al-Qamar",        arabicName: "القمر",       ayahs: 55,  revelation: "Meccan"  },
  { number: 55,  name: "Ar-Rahman",       arabicName: "الرحمن",      ayahs: 78,  revelation: "Medinan" },
  { number: 56,  name: "Al-Waqi'ah",      arabicName: "الواقعة",     ayahs: 96,  revelation: "Meccan"  },
  { number: 57,  name: "Al-Hadid",        arabicName: "الحديد",      ayahs: 29,  revelation: "Medinan" },
  { number: 58,  name: "Al-Mujadila",     arabicName: "المجادلة",    ayahs: 22,  revelation: "Medinan" },
  { number: 59,  name: "Al-Hashr",        arabicName: "الحشر",       ayahs: 24,  revelation: "Medinan" },
  { number: 60,  name: "Al-Mumtahanah",   arabicName: "الممتحنة",    ayahs: 13,  revelation: "Medinan" },
  { number: 61,  name: "As-Saff",         arabicName: "الصف",        ayahs: 14,  revelation: "Medinan" },
  { number: 62,  name: "Al-Jumu'ah",      arabicName: "الجمعة",      ayahs: 11,  revelation: "Medinan" },
  { number: 63,  name: "Al-Munafiqun",    arabicName: "المنافقون",   ayahs: 11,  revelation: "Medinan" },
  { number: 64,  name: "At-Taghabun",     arabicName: "التغابن",     ayahs: 18,  revelation: "Medinan" },
  { number: 65,  name: "At-Talaq",        arabicName: "الطلاق",      ayahs: 12,  revelation: "Medinan" },
  { number: 66,  name: "At-Tahrim",       arabicName: "التحريم",     ayahs: 12,  revelation: "Medinan" },
  { number: 67,  name: "Al-Mulk",         arabicName: "الملك",       ayahs: 30,  revelation: "Meccan"  },
  { number: 68,  name: "Al-Qalam",        arabicName: "القلم",       ayahs: 52,  revelation: "Meccan"  },
  { number: 69,  name: "Al-Haqqah",       arabicName: "الحاقة",      ayahs: 52,  revelation: "Meccan"  },
  { number: 70,  name: "Al-Ma'arij",      arabicName: "المعارج",     ayahs: 44,  revelation: "Meccan"  },
  { number: 71,  name: "Nuh",             arabicName: "نوح",         ayahs: 28,  revelation: "Meccan"  },
  { number: 72,  name: "Al-Jinn",         arabicName: "الجن",        ayahs: 28,  revelation: "Meccan"  },
  { number: 73,  name: "Al-Muzzammil",    arabicName: "المزمل",      ayahs: 20,  revelation: "Meccan"  },
  { number: 74,  name: "Al-Muddaththir",  arabicName: "المدثر",      ayahs: 56,  revelation: "Meccan"  },
  { number: 75,  name: "Al-Qiyamah",      arabicName: "القيامة",     ayahs: 40,  revelation: "Meccan"  },
  { number: 76,  name: "Al-Insan",        arabicName: "الإنسان",     ayahs: 31,  revelation: "Medinan" },
  { number: 77,  name: "Al-Mursalat",     arabicName: "المرسلات",    ayahs: 50,  revelation: "Meccan"  },
  { number: 78,  name: "An-Naba",         arabicName: "النبأ",       ayahs: 40,  revelation: "Meccan"  },
  { number: 79,  name: "An-Nazi'at",      arabicName: "النازعات",    ayahs: 46,  revelation: "Meccan"  },
  { number: 80,  name: "Abasa",           arabicName: "عبس",         ayahs: 42,  revelation: "Meccan"  },
  { number: 81,  name: "At-Takwir",       arabicName: "التكوير",     ayahs: 29,  revelation: "Meccan"  },
  { number: 82,  name: "Al-Infitar",      arabicName: "الإنفطار",    ayahs: 19,  revelation: "Meccan"  },
  { number: 83,  name: "Al-Mutaffifin",   arabicName: "المطففين",    ayahs: 36,  revelation: "Meccan"  },
  { number: 84,  name: "Al-Inshiqaq",     arabicName: "الانشقاق",    ayahs: 25,  revelation: "Meccan"  },
  { number: 85,  name: "Al-Buruj",        arabicName: "البروج",      ayahs: 22,  revelation: "Meccan"  },
  { number: 86,  name: "At-Tariq",        arabicName: "الطارق",      ayahs: 17,  revelation: "Meccan"  },
  { number: 87,  name: "Al-A'la",         arabicName: "الأعلى",      ayahs: 19,  revelation: "Meccan"  },
  { number: 88,  name: "Al-Ghashiyah",    arabicName: "الغاشية",     ayahs: 26,  revelation: "Meccan"  },
  { number: 89,  name: "Al-Fajr",         arabicName: "الفجر",       ayahs: 30,  revelation: "Meccan"  },
  { number: 90,  name: "Al-Balad",        arabicName: "البلد",       ayahs: 20,  revelation: "Meccan"  },
  { number: 91,  name: "Ash-Shams",       arabicName: "الشمس",       ayahs: 15,  revelation: "Meccan"  },
  { number: 92,  name: "Al-Layl",         arabicName: "الليل",       ayahs: 21,  revelation: "Meccan"  },
  { number: 93,  name: "Ad-Duha",         arabicName: "الضحى",       ayahs: 11,  revelation: "Meccan"  },
  { number: 94,  name: "Ash-Sharh",       arabicName: "الشرح",       ayahs: 8,   revelation: "Meccan"  },
  { number: 95,  name: "At-Tin",          arabicName: "التين",       ayahs: 8,   revelation: "Meccan"  },
  { number: 96,  name: "Al-Alaq",         arabicName: "العلق",       ayahs: 19,  revelation: "Meccan"  },
  { number: 97,  name: "Al-Qadr",         arabicName: "القدر",       ayahs: 5,   revelation: "Meccan"  },
  { number: 98,  name: "Al-Bayyinah",     arabicName: "البينة",      ayahs: 8,   revelation: "Medinan" },
  { number: 99,  name: "Az-Zalzalah",     arabicName: "الزلزلة",     ayahs: 8,   revelation: "Medinan" },
  { number: 100, name: "Al-Adiyat",       arabicName: "العاديات",    ayahs: 11,  revelation: "Meccan"  },
  { number: 101, name: "Al-Qari'ah",      arabicName: "القارعة",     ayahs: 11,  revelation: "Meccan"  },
  { number: 102, name: "At-Takathur",     arabicName: "التكاثر",     ayahs: 8,   revelation: "Meccan"  },
  { number: 103, name: "Al-Asr",          arabicName: "العصر",       ayahs: 3,   revelation: "Meccan"  },
  { number: 104, name: "Al-Humazah",      arabicName: "الهمزة",      ayahs: 9,   revelation: "Meccan"  },
  { number: 105, name: "Al-Fil",          arabicName: "الفيل",       ayahs: 5,   revelation: "Meccan"  },
  { number: 106, name: "Quraysh",         arabicName: "قريش",        ayahs: 4,   revelation: "Meccan"  },
  { number: 107, name: "Al-Ma'un",        arabicName: "الماعون",     ayahs: 7,   revelation: "Meccan"  },
  { number: 108, name: "Al-Kawthar",      arabicName: "الكوثر",      ayahs: 3,   revelation: "Meccan"  },
  { number: 109, name: "Al-Kafirun",      arabicName: "الكافرون",    ayahs: 6,   revelation: "Meccan"  },
  { number: 110, name: "An-Nasr",         arabicName: "النصر",       ayahs: 3,   revelation: "Medinan" },
  { number: 111, name: "Al-Masad",        arabicName: "المسد",       ayahs: 5,   revelation: "Meccan"  },
  { number: 112, name: "Al-Ikhlas",       arabicName: "الإخلاص",     ayahs: 4,   revelation: "Meccan"  },
  { number: 113, name: "Al-Falaq",        arabicName: "الفلق",       ayahs: 5,   revelation: "Meccan"  },
  { number: 114, name: "An-Nas",          arabicName: "الناس",       ayahs: 6,   revelation: "Meccan"  },
];

export function getSurahMeta(n: number): SurahMeta | undefined {
  return SURAH_META.find(s => s.number === n);
}
